function Dual_rectified_first_level_with_motion_only_confounds(varargin)
% =========================================================================
% SPM12 first-level and second-level GLM
%
% Dual-learning-rate Q-learning signed prediction error is entered as an
% outcome-locked parametric modulator. Confound regressors are included
% through SPM multi_reg.
%
% -------------------------------------------------------------------------
% Public-release version
% -------------------------------------------------------------------------
% This script contains no user-specific drive letters, user names, server
% addresses, or machine-specific absolute paths.
%
% Paths can be supplied using name-value arguments:
%
% Dual_rectified_first_level_with_motion_only_confounds( ...
%     'csv_dir', '/path/to/qlearning/trialwise_combined', ...
%     'onset_root', '/path/to/onsets', ...
%     'nii_dir', '/path/to/smoothed_4d_nifti', ...
%     'confounds_root', '/path/to/confounds', ...
%     'output_root', '/path/to/output');
%
% If no paths are supplied, the script uses the following directories
% relative to this MATLAB file:
%
%   data/qlearning/trialwise_combined
%   data/onsets
%   data/smoothed_4d_nifti
%   data/confounds
%   outputs/spm_dual_signed_pe
%
% -------------------------------------------------------------------------
% Expected input files
% -------------------------------------------------------------------------
%
% Trial-wise Q-learning CSV:
%   data/qlearning/trialwise_combined/
%       Qlearning_single_dual_trialwise_Sub02.csv
%
% Required CSV columns:
%   global_trial
%   vPE_dual
%
% Outcome onset file:
%   data/onsets/Sub02/Onset_outcome_all.mat
%
% Required MATLAB variable:
%   onset_outcome_all
%
% Four-dimensional NIfTI:
%   data/smoothed_4d_nifti/Sub02.nii
%
% Confound file:
%   data/confounds/Sub02/confunds.txt
%
% Each participant must have one subdirectory named using the same
% participant identifier as the Q-learning and NIfTI files.
%
% -------------------------------------------------------------------------
% Timing assumption
% -------------------------------------------------------------------------
% onset_outcome_all must be expressed in seconds relative to the beginning
% of the merged four-dimensional NIfTI file.
%
% If onset times restart from zero for each run, a multi-session GLM should
% be used instead of the merged-session model implemented here.
% =========================================================================

clearvars -except varargin;
clc;

% -------------------------------------------------------------------------
% Check SPM availability
% -------------------------------------------------------------------------

if exist('spm', 'file') ~= 2
    error( ...
        ['SPM was not found on the MATLAB path. ', ...
         'Install SPM12 and add it to the MATLAB path before running.'] ...
    );
end

spm('defaults', 'fmri');
spm_jobman('initcfg');

% -------------------------------------------------------------------------
% Parse portable path settings
% -------------------------------------------------------------------------

script_path = mfilename('fullpath');
script_dir = fileparts(script_path);

default_data_root = fullfile( ...
    script_dir, ...
    'data' ...
);

default_output_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'spm_dual_signed_pe' ...
);

parser = inputParser;

addParameter( ...
    parser, ...
    'csv_dir', ...
    fullfile( ...
        default_data_root, ...
        'qlearning', ...
        'trialwise_combined' ...
    ), ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'onset_root', ...
    fullfile( ...
        default_data_root, ...
        'onsets' ...
    ), ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'nii_dir', ...
    fullfile( ...
        default_data_root, ...
        'smoothed_4d_nifti' ...
    ), ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'confounds_root', ...
    fullfile( ...
        default_data_root, ...
        'confounds' ...
    ), ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'output_root', ...
    default_output_root, ...
    @(x) ischar(x) || isstring(x) ...
);

parse(parser, varargin{:});

csv_dir = char(parser.Results.csv_dir);
onset_root = char(parser.Results.onset_root);
nii_dir = char(parser.Results.nii_dir);
confounds_root = char(parser.Results.confounds_root);
output_root = char(parser.Results.output_root);

% -------------------------------------------------------------------------
% Model settings
% -------------------------------------------------------------------------

PE_COLUMN = 'vPE_dual';

% true: z-score signed PE within each participant.
DO_ZSCORE = true;

OUTCOME_DURATION = 0.5;
RT = 2.2;

FMRI_T = 16;
FMRI_T0 = 8;

HPF = 128;

OVERWRITE_FIRST_LEVEL = true;
RUN_SECOND_LEVEL = true;

% If true, a participant is skipped when confunds.txt is missing or its
% row count does not match the number of NIfTI volumes.
REQUIRE_CONFOUNDS = true;

% -------------------------------------------------------------------------
% Validate input directories
% -------------------------------------------------------------------------

required_directories = {
    csv_dir, ...
    onset_root, ...
    nii_dir ...
};

required_directory_names = {
    'Trial-wise CSV directory', ...
    'Outcome onset root', ...
    'Four-dimensional NIfTI directory' ...
};

for directory_index = 1:numel(required_directories)

    current_directory = ...
        required_directories{directory_index};

    if ~exist(current_directory, 'dir')
        error( ...
            '%s does not exist:\n%s', ...
            required_directory_names{directory_index}, ...
            current_directory ...
        );
    end
end

if REQUIRE_CONFOUNDS && ~exist(confounds_root, 'dir')
    error( ...
        ['Confounds root does not exist, but ', ...
         'REQUIRE_CONFOUNDS is true:\n%s'], ...
        confounds_root ...
    );
end

if ~exist(output_root, 'dir')
    mkdir(output_root);
end

% -------------------------------------------------------------------------
% Start log
% -------------------------------------------------------------------------

diary_file = fullfile( ...
    output_root, ...
    [ ...
        'log_dual_signed_PE_GLM_', ...
        datestr(now, 'yyyymmdd_HHMMSS'), ...
        '.txt' ...
    ] ...
);

diary(diary_file);

fprintf('\n============================================================\n');
fprintf('Dual-learning-rate signed PE parametric-modulation GLM\n');
fprintf('SPM first-level and second-level analyses\n');
fprintf('============================================================\n\n');

fprintf('Trial-wise CSV directory: %s\n', csv_dir);
fprintf('Outcome onset root:       %s\n', onset_root);
fprintf('4D NIfTI directory:       %s\n', nii_dir);
fprintf('Confounds root:           %s\n', confounds_root);
fprintf('Output root:              %s\n', output_root);
fprintf('PE column:                %s\n', PE_COLUMN);
fprintf('Z-score PE:               %d\n', DO_ZSCORE);
fprintf('Outcome duration:         %.3f seconds\n', OUTCOME_DURATION);
fprintf('TR:                       %.3f seconds\n', RT);
fprintf('High-pass filter:         %.3f seconds\n', HPF);
fprintf('Require confounds:        %d\n\n', REQUIRE_CONFOUNDS);

% -------------------------------------------------------------------------
% Find trial-wise CSV files
% -------------------------------------------------------------------------

csv_files = dir( ...
    fullfile( ...
        csv_dir, ...
        'Qlearning_single_dual_trialwise_Sub*.csv' ...
    ) ...
);

if isempty(csv_files)
    error( ...
        ['No files matching ', ...
         'Qlearning_single_dual_trialwise_Sub*.csv were found in:\n%s'], ...
        csv_dir ...
    );
end

fprintf( ...
    'Found %d trial-wise Q-learning CSV files.\n', ...
    numel(csv_files) ...
);

% -------------------------------------------------------------------------
% Containers for second-level analyses
% -------------------------------------------------------------------------

con_outcome = {};
con_pe_pos = {};
con_pe_neg = {};

finished_subjects = {};
used_confounds = {};

% -------------------------------------------------------------------------
% First-level loop
% -------------------------------------------------------------------------

for participant_index = 1:numel(csv_files)

    csv_name = csv_files(participant_index).name;
    csv_path = fullfile(csv_dir, csv_name);

    subject_token = regexp( ...
        csv_name, ...
        'Qlearning_single_dual_trialwise_(Sub\d+)\.csv', ...
        'tokens', ...
        'once' ...
    );

    if isempty(subject_token)
        fprintf( ...
            '\nCould not parse participant ID from filename; skipped: %s\n', ...
            csv_name ...
        );
        continue;
    end

    subject_id_raw = subject_token{1};

    subject_digits = regexp( ...
        subject_id_raw, ...
        '\d+', ...
        'match', ...
        'once' ...
    );

    subject_number = str2double(subject_digits);
    subject_id = sprintf('Sub%02d', subject_number);

    fprintf('\n============================================================\n');
    fprintf( ...
        'Participant %d/%d: %s\n', ...
        participant_index, ...
        numel(csv_files), ...
        subject_id ...
    );
    fprintf('CSV file: %s\n', csv_path);

    try
        % -----------------------------------------------------------------
        % Read trial-wise Q-learning CSV
        % -----------------------------------------------------------------

        trial_table = readtable(csv_path);

        if ~ismember( ...
                'global_trial', ...
                trial_table.Properties.VariableNames ...
            )

            error( ...
                'CSV does not contain the required global_trial column.' ...
            );
        end

        if ~ismember( ...
                PE_COLUMN, ...
                trial_table.Properties.VariableNames ...
            )

            error( ...
                'CSV does not contain the required PE column: %s', ...
                PE_COLUMN ...
            );
        end

        trial_table = sortrows( ...
            trial_table, ...
            'global_trial' ...
        );

        signed_pe_raw = double( ...
            trial_table.(PE_COLUMN) ...
        );

        signed_pe_raw = signed_pe_raw(:);

        if DO_ZSCORE
            signed_pe = local_zscore(signed_pe_raw);

            fprintf( ...
                ['Using z-scored signed PE: ', ...
                 'mean=%.6f, SD=%.6f, min=%.6f, max=%.6f\n'], ...
                local_nanmean(signed_pe), ...
                local_nanstd(signed_pe), ...
                min(signed_pe), ...
                max(signed_pe) ...
            );
        else
            signed_pe = signed_pe_raw;

            fprintf( ...
                ['Using raw signed PE: ', ...
                 'mean=%.6f, SD=%.6f, min=%.6f, max=%.6f\n'], ...
                local_nanmean(signed_pe), ...
                local_nanstd(signed_pe), ...
                min(signed_pe), ...
                max(signed_pe) ...
            );
        end

        % -----------------------------------------------------------------
        % Read outcome onset file
        % -----------------------------------------------------------------

        onset_path = fullfile( ...
            onset_root, ...
            subject_id, ...
            'Onset_outcome_all.mat' ...
        );

        if ~exist(onset_path, 'file')
            fprintf( ...
                'Missing outcome onset file: %s\n', ...
                onset_path ...
            );
            continue;
        end

        onset_data = load(onset_path);

        if ~isfield(onset_data, 'onset_outcome_all')
            fprintf( ...
                ['Variable onset_outcome_all was not found ', ...
                 'in the following file:\n%s\n'], ...
                onset_path ...
            );
            continue;
        end

        outcome_onsets = onset_data.onset_outcome_all;

        if iscell(outcome_onsets)
            outcome_onsets = cell2mat(outcome_onsets);
        end

        outcome_onsets = double(outcome_onsets(:));

        fprintf( ...
            'Outcome-onset length = %d; PE length = %d\n', ...
            numel(outcome_onsets), ...
            numel(signed_pe) ...
        );

        if numel(outcome_onsets) ~= numel(signed_pe)
            fprintf( ...
                ['Length mismatch between outcome onsets and PE values. ', ...
                 'Participant skipped: %s\n'], ...
                subject_id ...
            );
            continue;
        end

        if any(diff(outcome_onsets) < 0)
            fprintf( ...
                ['Outcome onsets decrease at least once, suggesting ', ...
                 'that onset timing may restart within each run.\n'] ...
            );

            fprintf( ...
                ['This script assumes merged-session timing. ', ...
                 'Participant skipped: %s\n'], ...
                subject_id ...
            );
            continue;
        end

        valid_trials = ...
            isfinite(outcome_onsets) ...
            & isfinite(signed_pe);

        number_invalid_trials = sum(~valid_trials);

        if number_invalid_trials > 0
            fprintf( ...
                ['Removed %d trials with non-finite onset ', ...
                 'or prediction-error values.\n'], ...
                number_invalid_trials ...
            );

            outcome_onsets = ...
                outcome_onsets(valid_trials);

            signed_pe = ...
                signed_pe(valid_trials);
        end

        % -----------------------------------------------------------------
        % Read four-dimensional NIfTI
        % -----------------------------------------------------------------

        nii_path = fullfile( ...
            nii_dir, ...
            [subject_id, '.nii'] ...
        );

        if ~exist(nii_path, 'file')

            alternative_nii_path = ...
                [nii_path, '.gz'];

            if exist(alternative_nii_path, 'file')
                nii_path = alternative_nii_path;
            else
                fprintf( ...
                    'Missing four-dimensional NIfTI file: %s\n', ...
                    nii_path ...
                );
                continue;
            end
        end

        nifti_volumes = spm_vol(nii_path);
        number_of_volumes = numel(nifti_volumes);

        scans = cell(number_of_volumes, 1);

        for volume_index = 1:number_of_volumes
            scans{volume_index} = sprintf( ...
                '%s,%d', ...
                nii_path, ...
                volume_index ...
            );
        end

        fprintf( ...
            'Number of NIfTI volumes = %d\n', ...
            number_of_volumes ...
        );

        scan_duration = ...
            number_of_volumes * RT;

        if max(outcome_onsets) > scan_duration

            fprintf( ...
                ['Warning: maximum outcome onset %.3f seconds exceeds ', ...
                 'scan duration %.3f seconds.\n'], ...
                max(outcome_onsets), ...
                scan_duration ...
            );

            fprintf( ...
                ['Check whether onset times are correctly aligned ', ...
                 'with the merged four-dimensional NIfTI file.\n'] ...
            );
        end

        % -----------------------------------------------------------------
        % Read fixed confunds.txt file
        % -----------------------------------------------------------------

        confounds_file = fullfile( ...
            confounds_root, ...
            subject_id, ...
            'confunds.txt' ...
        );

        if ~exist(confounds_file, 'file')

            fprintf( ...
                'Missing confunds.txt for %s: %s\n', ...
                subject_id, ...
                confounds_file ...
            );

            if REQUIRE_CONFOUNDS
                fprintf( ...
                    ['REQUIRE_CONFOUNDS is true. ', ...
                     'Participant skipped: %s\n'], ...
                    subject_id ...
                );
                continue;
            else
                multi_reg_cell = {''};
                used_confounds_file = '';

                fprintf( ...
                    ['Proceeding without confounds because ', ...
                     'REQUIRE_CONFOUNDS is false.\n'] ...
                );
            end

        else
            fprintf( ...
                'Confounds file: %s\n', ...
                confounds_file ...
            );

            try
                confound_matrix = load(confounds_file);
            catch
                confound_matrix = readmatrix(confounds_file);
            end

            if ~isnumeric(confound_matrix)
                error( ...
                    'Confunds file did not contain a numeric matrix: %s', ...
                    confounds_file ...
                );
            end

            if size(confound_matrix, 1) ~= number_of_volumes

                fprintf( ...
                    ['Confounds row count mismatch for %s: ', ...
                     'confound rows=%d, NIfTI volumes=%d.\n'], ...
                    subject_id, ...
                    size(confound_matrix, 1), ...
                    number_of_volumes ...
                );

                if REQUIRE_CONFOUNDS
                    fprintf( ...
                        ['REQUIRE_CONFOUNDS is true. ', ...
                         'Participant skipped: %s\n'], ...
                        subject_id ...
                    );
                    continue;
                else
                    multi_reg_cell = {''};
                    used_confounds_file = '';

                    fprintf( ...
                        ['Proceeding without confounds because ', ...
                         'REQUIRE_CONFOUNDS is false.\n'] ...
                    );
                end

            else
                if any(~isfinite(confound_matrix(:)))

                    fprintf( ...
                        ['Confounds contain NaN or Inf. ', ...
                         'Non-finite values will be replaced with zero.\n'] ...
                    );

                    confound_matrix( ...
                        ~isfinite(confound_matrix) ...
                    ) = 0;

                    cleaned_confounds_dir = fullfile( ...
                        output_root, ...
                        'cleaned_confounds', ...
                        subject_id ...
                    );

                    if ~exist(cleaned_confounds_dir, 'dir')
                        mkdir(cleaned_confounds_dir);
                    end

                    cleaned_file = fullfile( ...
                        cleaned_confounds_dir, ...
                        'confunds.txt' ...
                    );

                    save_matrix_txt( ...
                        cleaned_file, ...
                        confound_matrix ...
                    );

                    confounds_file = cleaned_file;

                    fprintf( ...
                        'Cleaned confounds saved: %s\n', ...
                        confounds_file ...
                    );
                end

                multi_reg_cell = {
                    confounds_file
                };

                used_confounds_file = ...
                    confounds_file;

                fprintf( ...
                    ['Using confounds as SPM multi_reg: ', ...
                     'rows=%d, regressors=%d\n'], ...
                    size(confound_matrix, 1), ...
                    size(confound_matrix, 2) ...
                );
            end
        end

        % -----------------------------------------------------------------
        % Define first-level output folder
        % -----------------------------------------------------------------

        first_level_dir = fullfile( ...
            output_root, ...
            'first_level', ...
            subject_id ...
        );

        if exist(first_level_dir, 'dir') ...
                && OVERWRITE_FIRST_LEVEL

            fprintf( ...
                'Removing previous first-level directory: %s\n', ...
                first_level_dir ...
            );

            rmdir(first_level_dir, 's');
        end

        if ~exist(first_level_dir, 'dir')
            mkdir(first_level_dir);
        end

        existing_spm_mat = fullfile( ...
            first_level_dir, ...
            'SPM.mat' ...
        );

        if exist(existing_spm_mat, 'file') ...
                && ~OVERWRITE_FIRST_LEVEL

            fprintf( ...
                ['Existing SPM.mat detected and ', ...
                 'OVERWRITE_FIRST_LEVEL is false. ', ...
                 'Specification and estimation skipped.\n'] ...
            );

        else
            % -------------------------------------------------------------
            % First-level specification and estimation
            % -------------------------------------------------------------

            clear matlabbatch;

            matlabbatch{1}.spm.stats.fmri_spec.dir = {
                first_level_dir
            };

            matlabbatch{1}.spm.stats.fmri_spec.timing.units = ...
                'secs';

            matlabbatch{1}.spm.stats.fmri_spec.timing.RT = ...
                RT;

            matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t = ...
                FMRI_T;

            matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t0 = ...
                FMRI_T0;

            matlabbatch{1}.spm.stats.fmri_spec.sess.scans = ...
                scans;

            % Outcome main effect.
            matlabbatch{1}.spm.stats.fmri_spec.sess.cond(1).name = ...
                'Outcome_Onset';

            matlabbatch{1}.spm.stats.fmri_spec.sess.cond(1).onset = ...
                outcome_onsets(:);

            matlabbatch{1}.spm.stats.fmri_spec.sess.cond(1).duration = ...
                OUTCOME_DURATION;

            matlabbatch{1}.spm.stats.fmri_spec.sess.cond(1).tmod = ...
                0;

            % Signed PE parametric modulator.
            matlabbatch{1}.spm.stats.fmri_spec.sess.cond(1) ...
                .pmod(1).name = ...
                'dual_signed_PE';

            matlabbatch{1}.spm.stats.fmri_spec.sess.cond(1) ...
                .pmod(1).param = ...
                signed_pe(:);

            matlabbatch{1}.spm.stats.fmri_spec.sess.cond(1) ...
                .pmod(1).poly = ...
                1;

            % Disable SPM parametric-modulator orthogonalization.
            matlabbatch{1}.spm.stats.fmri_spec.sess.cond(1).orth = ...
                0;

            matlabbatch{1}.spm.stats.fmri_spec.sess.multi = ...
                {''};

            matlabbatch{1}.spm.stats.fmri_spec.sess.regress = ...
                struct( ...
                    'name', {}, ...
                    'val', {} ...
                );

            % Confounds enter through SPM multi_reg.
            matlabbatch{1}.spm.stats.fmri_spec.sess.multi_reg = ...
                multi_reg_cell;

            % Low-frequency drift removal.
            matlabbatch{1}.spm.stats.fmri_spec.sess.hpf = ...
                HPF;

            matlabbatch{1}.spm.stats.fmri_spec.fact = ...
                struct( ...
                    'name', {}, ...
                    'levels', {} ...
                );

            matlabbatch{1}.spm.stats.fmri_spec.bases.hrf.derivs = ...
                [0, 0];

            matlabbatch{1}.spm.stats.fmri_spec.volt = ...
                1;

            matlabbatch{1}.spm.stats.fmri_spec.global = ...
                'None';

            matlabbatch{1}.spm.stats.fmri_spec.mthresh = ...
                0.8;

            matlabbatch{1}.spm.stats.fmri_spec.mask = ...
                {''};

            matlabbatch{1}.spm.stats.fmri_spec.cvi = ...
                'AR(1)';

            matlabbatch{2}.spm.stats.fmri_est.spmmat = {
                fullfile( ...
                    first_level_dir, ...
                    'SPM.mat' ...
                )
            };

            matlabbatch{2}.spm.stats.fmri_est.write_residuals = ...
                0;

            matlabbatch{2}.spm.stats.fmri_est.method.Classical = ...
                1;

            batch_path = fullfile( ...
                first_level_dir, ...
                [ ...
                    'batch_spec_est_', ...
                    subject_id, ...
                    '_dual_signed_PE.mat' ...
                ] ...
            );

            save( ...
                batch_path, ...
                'matlabbatch' ...
            );

            fprintf( ...
                'Saved specification and estimation batch: %s\n', ...
                batch_path ...
            );

            fprintf( ...
                'Running first-level specification and estimation...\n' ...
            );

            spm_jobman( ...
                'run', ...
                matlabbatch ...
            );

            fprintf( ...
                'First-level estimation finished: %s\n', ...
                subject_id ...
            );

            % Create exact-length contrasts after SPM.mat exists.
            create_first_level_contrasts( ...
                first_level_dir ...
            );
        end

        % -----------------------------------------------------------------
        % Collect contrast images
        % -----------------------------------------------------------------

        outcome_contrast = fullfile( ...
            first_level_dir, ...
            'con_0001.nii' ...
        );

        positive_pe_contrast = fullfile( ...
            first_level_dir, ...
            'con_0002.nii' ...
        );

        negative_pe_contrast = fullfile( ...
            first_level_dir, ...
            'con_0003.nii' ...
        );

        if exist(outcome_contrast, 'file') ...
                && exist(positive_pe_contrast, 'file') ...
                && exist(negative_pe_contrast, 'file')

            con_outcome{end + 1, 1} = ...
                outcome_contrast; %#ok<AGROW>

            con_pe_pos{end + 1, 1} = ...
                positive_pe_contrast; %#ok<AGROW>

            con_pe_neg{end + 1, 1} = ...
                negative_pe_contrast; %#ok<AGROW>

            finished_subjects{end + 1, 1} = ...
                subject_id; %#ok<AGROW>

            used_confounds{end + 1, 1} = ...
                used_confounds_file; %#ok<AGROW>

        else
            fprintf( ...
                ['One or more contrast images are missing. ', ...
                 'Participant not included in second-level analyses: %s\n'], ...
                subject_id ...
            );
        end

    catch analysis_error

        fprintf( ...
            'Participant %s failed: %s\n', ...
            subject_id, ...
            analysis_error.message ...
        );

        fprintf( ...
            '%s\n', ...
            getReport( ...
                analysis_error, ...
                'extended' ...
            ) ...
        );

        continue;
    end
end

fprintf('\n============================================================\n');

fprintf( ...
    'First-level analyses finished. Collected %d participants.\n', ...
    numel(finished_subjects) ...
);

fprintf('============================================================\n');

% -------------------------------------------------------------------------
% Save first-level completion manifest
% -------------------------------------------------------------------------

finished_table = table( ...
    finished_subjects, ...
    con_outcome, ...
    con_pe_pos, ...
    con_pe_neg, ...
    used_confounds, ...
    'VariableNames', { ...
        'subject', ...
        'con_outcome', ...
        'con_dual_PE_positive', ...
        'con_dual_PE_negative', ...
        'confounds_file' ...
    } ...
);

finished_table_path = fullfile( ...
    output_root, ...
    'finished_subjects_contrasts.csv' ...
);

writetable( ...
    finished_table, ...
    finished_table_path ...
);

fprintf( ...
    'Saved participant and contrast manifest: %s\n', ...
    finished_table_path ...
);

% -------------------------------------------------------------------------
% Second-level one-sample t-tests
% -------------------------------------------------------------------------

if RUN_SECOND_LEVEL

    if numel(finished_subjects) < 2

        fprintf( ...
            ['Fewer than two participants are available. ', ...
             'Second-level analyses skipped.\n'] ...
        );

    else
        fprintf( ...
            '\nRunning second-level one-sample t-tests...\n' ...
        );

        run_second_level_onesample( ...
            con_pe_pos, ...
            fullfile( ...
                output_root, ...
                'second_level', ...
                'dual_signed_PE_positive' ...
            ), ...
            'Group dual signed PE positive' ...
        );

        run_second_level_onesample( ...
            con_pe_neg, ...
            fullfile( ...
                output_root, ...
                'second_level', ...
                'dual_signed_PE_negative' ...
            ), ...
            'Group dual signed PE negative' ...
        );

        run_second_level_onesample( ...
            con_outcome, ...
            fullfile( ...
                output_root, ...
                'second_level', ...
                'outcome_main_effect' ...
            ), ...
            'Group outcome main effect' ...
        );

        fprintf( ...
            'Second-level analyses finished.\n' ...
        );
    end

else
    fprintf( ...
        ['RUN_SECOND_LEVEL is false. ', ...
         'Second-level analyses skipped.\n'] ...
    );
end

fprintf('\nAll analyses completed.\n');
fprintf('Log file: %s\n', diary_file);

diary off;

end


% =========================================================================
% Local helper functions
% =========================================================================

function create_first_level_contrasts(first_level_dir)
% Create exact-length contrast vectors after SPM.mat exists.
%
% Confound regressors expand the design matrix, so contrast vectors are
% constructed after estimation using the actual design-matrix length.

spm_mat = fullfile( ...
    first_level_dir, ...
    'SPM.mat' ...
);

if ~exist(spm_mat, 'file')
    error( ...
        'SPM.mat was not found: %s', ...
        spm_mat ...
    );
end

loaded_spm = load(spm_mat);
SPM = loaded_spm.SPM;

column_names = SPM.xX.name;
number_of_columns = size(SPM.xX.X, 2);

outcome_column_index = find_column_index( ...
    column_names, ...
    'Outcome_Onset*bf(1)' ...
);

pe_column_index = find_column_index( ...
    column_names, ...
    'dual_signed_PE' ...
);

if isempty(outcome_column_index)

    fprintf('Design-matrix columns:\n');
    disp(column_names(:));

    error( ...
        'Could not identify the Outcome_Onset main-effect column.' ...
    );
end

if isempty(pe_column_index)

    fprintf('Design-matrix columns:\n');
    disp(column_names(:));

    error( ...
        'Could not identify the dual_signed_PE parametric-modulator column.' ...
    );
end

outcome_weights = zeros( ...
    1, ...
    number_of_columns ...
);

positive_pe_weights = zeros( ...
    1, ...
    number_of_columns ...
);

negative_pe_weights = zeros( ...
    1, ...
    number_of_columns ...
);

outcome_weights(outcome_column_index) = 1;
positive_pe_weights(pe_column_index) = 1;
negative_pe_weights(pe_column_index) = -1;

clear matlabbatch;

matlabbatch{1}.spm.stats.con.spmmat = {
    spm_mat
};

matlabbatch{1}.spm.stats.con.consess{1}.tcon.name = ...
    'Outcome > baseline';

matlabbatch{1}.spm.stats.con.consess{1}.tcon.weights = ...
    outcome_weights;

matlabbatch{1}.spm.stats.con.consess{1}.tcon.sessrep = ...
    'none';

matlabbatch{1}.spm.stats.con.consess{2}.tcon.name = ...
    'dual_signed_PE positive';

matlabbatch{1}.spm.stats.con.consess{2}.tcon.weights = ...
    positive_pe_weights;

matlabbatch{1}.spm.stats.con.consess{2}.tcon.sessrep = ...
    'none';

matlabbatch{1}.spm.stats.con.consess{3}.tcon.name = ...
    'dual_signed_PE negative';

matlabbatch{1}.spm.stats.con.consess{3}.tcon.weights = ...
    negative_pe_weights;

matlabbatch{1}.spm.stats.con.consess{3}.tcon.sessrep = ...
    'none';

matlabbatch{1}.spm.stats.con.delete = ...
    1;

contrast_batch_path = fullfile( ...
    first_level_dir, ...
    'batch_contrasts_dual_signed_PE.mat' ...
);

save( ...
    contrast_batch_path, ...
    'matlabbatch' ...
);

fprintf( ...
    ['Creating contrasts using the exact design length ', ...
     'of %d columns.\n'], ...
    number_of_columns ...
);

fprintf( ...
    'Outcome column index = %d; PE column index = %d\n', ...
    outcome_column_index, ...
    pe_column_index ...
);

spm_jobman( ...
    'run', ...
    matlabbatch ...
);

end


function column_index = find_column_index( ...
    column_names, ...
    required_string ...
)
% Return the first design-matrix column containing required_string.

column_index = [];

for index = 1:numel(column_names)

    current_name = column_names{index};

    if ~isempty( ...
            strfind( ...
                current_name, ...
                required_string ...
            ) ...
        ) %#ok<STREMP>

        column_index = index;
        return;
    end
end

end


function run_second_level_onesample( ...
    contrast_images, ...
    output_directory, ...
    contrast_name ...
)
% Run an SPM second-level one-sample t-test.

if exist(output_directory, 'dir')
    rmdir(output_directory, 's');
end

mkdir(output_directory);

clear matlabbatch;

matlabbatch{1}.spm.stats.factorial_design.dir = {
    output_directory
};

matlabbatch{1}.spm.stats.factorial_design.des.t1.scans = ...
    contrast_images;

matlabbatch{1}.spm.stats.factorial_design.cov = ...
    struct( ...
        'c', {}, ...
        'cname', {}, ...
        'iCFI', {}, ...
        'iCC', {} ...
    );

matlabbatch{1}.spm.stats.factorial_design.multi_cov = ...
    struct( ...
        'files', {}, ...
        'iCFI', {}, ...
        'iCC', {} ...
    );

matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = ...
    1;

matlabbatch{1}.spm.stats.factorial_design.masking.im = ...
    1;

matlabbatch{1}.spm.stats.factorial_design.masking.em = ...
    {''};

matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = ...
    1;

matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = ...
    1;

matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = ...
    1;

matlabbatch{2}.spm.stats.fmri_est.spmmat = {
    fullfile( ...
        output_directory, ...
        'SPM.mat' ...
    )
};

matlabbatch{2}.spm.stats.fmri_est.write_residuals = ...
    0;

matlabbatch{2}.spm.stats.fmri_est.method.Classical = ...
    1;

matlabbatch{3}.spm.stats.con.spmmat = {
    fullfile( ...
        output_directory, ...
        'SPM.mat' ...
    )
};

matlabbatch{3}.spm.stats.con.consess{1}.tcon.name = ...
    contrast_name;

matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights = ...
    1;

matlabbatch{3}.spm.stats.con.consess{1}.tcon.sessrep = ...
    'none';

matlabbatch{3}.spm.stats.con.delete = ...
    1;

safe_contrast_name = regexprep( ...
    contrast_name, ...
    '\s+', ...
    '_' ...
);

second_level_batch_path = fullfile( ...
    output_directory, ...
    [ ...
        'batch_secondlevel_', ...
        safe_contrast_name, ...
        '.mat' ...
    ] ...
);

save( ...
    second_level_batch_path, ...
    'matlabbatch' ...
);

fprintf( ...
    'Running second-level contrast: %s\n', ...
    contrast_name ...
);

fprintf( ...
    'Second-level output: %s\n', ...
    output_directory ...
);

fprintf( ...
    'Number of contrast images: %d\n', ...
    numel(contrast_images) ...
);

spm_jobman( ...
    'run', ...
    matlabbatch ...
);

end


function standardized_values = local_zscore(values)
% Version-stable z-scoring that ignores NaN and Inf.

mean_value = local_nanmean(values);
standard_deviation = local_nanstd(values);

if standard_deviation == 0 ...
        || isnan(standard_deviation)

    standardized_values = ...
        values * 0;
else
    standardized_values = ...
        (values - mean_value) ...
        ./ standard_deviation;
end

end


function mean_value = local_nanmean(values)
% Version-stable mean excluding non-finite values.

values = values(isfinite(values));

if isempty(values)
    mean_value = NaN;
else
    mean_value = mean(values);
end

end


function standard_deviation = local_nanstd(values)
% Version-stable standard deviation excluding non-finite values.

values = values(isfinite(values));

if numel(values) < 2
    standard_deviation = NaN;
else
    standard_deviation = std(values);
end

end


function save_matrix_txt(filename, numeric_matrix)
% Save a numeric matrix as a plain-text file.

file_id = fopen( ...
    filename, ...
    'w' ...
);

if file_id == -1
    error( ...
        'Cannot open file for writing: %s', ...
        filename ...
    );
end

if isempty(numeric_matrix)
    fclose(file_id);
    return;
end

if size(numeric_matrix, 2) == 1

    format_string = ...
        '%.6f\n';

else
    format_string = [
        repmat( ...
            '%.6f ', ...
            1, ...
            size(numeric_matrix, 2) - 1 ...
        ), ...
        '%.6f\n' ...
    ];
end

for row_index = 1:size(numeric_matrix, 1)

    fprintf( ...
        file_id, ...
        format_string, ...
        numeric_matrix(row_index, :) ...
    );
end

fclose(file_id);

end