function run_second_level_one_sample_tests(varargin)
% =========================================================================
% SPM12 second-level one-sample t-tests for first-level slope maps
%
% For each ROI and learning phase, this script:
%
%   1. Collects participant-level slope maps.
%   2. Specifies a second-level one-sample t-test.
%   3. Estimates the group-level model.
%   4. Creates positive and negative one-sample t-contrasts.
%
% The participant-level input maps are expected to represent voxel-wise
% regression slopes from the first-level analysis.
%
% -------------------------------------------------------------------------
% Expected input structure
% -------------------------------------------------------------------------
%
% <first_level_root>/
% ├── ROI_1/
% │   ├── Sub02/
% │   │   ├── Sub02_ROI_1_regBeta_GMresid_LE.nii
% │   │   └── Sub02_ROI_1_regBeta_GMresid_RN.nii
% │   ├── Sub03/
% │   │   └── ...
% │   └── ...
% ├── ROI_2/
% │   └── ...
% └── ...
%
% -------------------------------------------------------------------------
% Output structure
% -------------------------------------------------------------------------
%
% <second_level_root>/
% ├── ROI_1/
% │   ├── LE/
% │   │   ├── SPM.mat
% │   │   ├── con_0001.nii
% │   │   ├── con_0002.nii
% │   │   ├── spmT_0001.nii
% │   │   ├── spmT_0002.nii
% │   │   └── included_subjects.txt
% │   └── RN/
% │       └── ...
% ├── ROI_2/
% │   └── ...
% └── second_level_summary.tsv
%
% -------------------------------------------------------------------------
% Default paths
% -------------------------------------------------------------------------
%
% Paths are resolved relative to the location of this MATLAB file:
%
%   First-level input:
%       outputs/roi_pattern_regression/
%
%   Second-level output:
%       outputs/roi_pattern_regression_second_level/
%
% -------------------------------------------------------------------------
% Example
% -------------------------------------------------------------------------
%
% run_second_level_one_sample_tests( ...
%     'first_level_root', '/path/to/first_level_maps', ...
%     'second_level_root', '/path/to/second_level_results', ...
%     'explicit_mask', '/path/to/group_mask.nii', ...
%     'phases', {'LE', 'RN'});
%
% To prevent replacement of an existing SPM model:
%
% run_second_level_one_sample_tests( ...
%     'overwrite_existing', false);
%
% -------------------------------------------------------------------------
% Notes
% -------------------------------------------------------------------------
%
% - Both .nii and .nii.gz input maps are accepted.
% - Compressed NIfTI files are decompressed into an internal cache because
%   SPM generally expects uncompressed .nii files.
% - The script removes only known SPM output files when replacing an
%   existing model. It does not delete the entire output directory.
% - At least two participant maps are required by default.
%
% Dependency
% ----------
% SPM12
% =========================================================================

clc;

%% ========================================================================
% 0. Parse input settings
% ========================================================================

script_path = mfilename('fullpath');
script_dir = fileparts(script_path);

default_first_level_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'roi_pattern_regression' ...
);

default_second_level_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'roi_pattern_regression_second_level' ...
);

parser = inputParser;

addParameter( ...
    parser, ...
    'first_level_root', ...
    default_first_level_root, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'second_level_root', ...
    default_second_level_root, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'explicit_mask', ...
    '', ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'phases', ...
    {'LE', 'RN'}, ...
    @(x) iscell(x) || ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'minimum_scans', ...
    2, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 2 ...
);

addParameter( ...
    parser, ...
    'overwrite_existing', ...
    true, ...
    @(x) islogical(x) && isscalar(x) ...
);

addParameter( ...
    parser, ...
    'affine_tolerance', ...
    1e-4, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0 ...
);

parse(parser, varargin{:});

first_level_root = char( ...
    parser.Results.first_level_root ...
);

second_level_root = char( ...
    parser.Results.second_level_root ...
);

explicit_mask = char( ...
    parser.Results.explicit_mask ...
);

phases = normalize_phase_list( ...
    parser.Results.phases ...
);

minimum_scans = parser.Results.minimum_scans;

overwrite_existing = ...
    parser.Results.overwrite_existing;

affine_tolerance = ...
    parser.Results.affine_tolerance;

%% ========================================================================
% 1. Validate software and paths
% ========================================================================

if exist('spm', 'file') ~= 2
    error( ...
        ['SPM12 was not found on the MATLAB path. ', ...
         'Install SPM12 and add it to the MATLAB path.'] ...
    );
end

if exist(first_level_root, 'dir') ~= 7
    error( ...
        'First-level root directory does not exist:\n%s', ...
        first_level_root ...
    );
end

if exist(second_level_root, 'dir') ~= 7
    mkdir(second_level_root);
end

if ...
        ~isempty(explicit_mask) ...
        && exist(explicit_mask, 'file') ~= 2

    error( ...
        'Explicit mask does not exist:\n%s', ...
        explicit_mask ...
    );
end

input_cache_root = fullfile( ...
    second_level_root, ...
    '_spm_input_cache' ...
);

if exist(input_cache_root, 'dir') ~= 7
    mkdir(input_cache_root);
end

fprintf('\n============================================================\n');
fprintf('SPM12 second-level one-sample t-tests\n');
fprintf('============================================================\n');

fprintf( ...
    'First-level root:    %s\n', ...
    first_level_root ...
);

fprintf( ...
    'Second-level root:   %s\n', ...
    second_level_root ...
);

fprintf( ...
    'Phases:              %s\n', ...
    strjoin(phases, ', ') ...
);

fprintf( ...
    'Minimum scans:       %d\n', ...
    minimum_scans ...
);

fprintf( ...
    'Overwrite existing:  %d\n', ...
    overwrite_existing ...
);

if isempty(explicit_mask)
    fprintf('Explicit mask:       none\n');
else
    fprintf( ...
        'Explicit mask:       %s\n', ...
        explicit_mask ...
    );
end

fprintf('============================================================\n');

%% ========================================================================
% 2. Initialize SPM
% ========================================================================

spm('Defaults', 'fMRI');
spm_jobman('initcfg');

%% ========================================================================
% 3. Prepare the optional explicit mask
% ========================================================================

if isempty(explicit_mask)

    prepared_explicit_mask = '';

else
    mask_cache_directory = fullfile( ...
        input_cache_root, ...
        'explicit_mask' ...
    );

    prepared_mask_path = prepare_spm_nifti( ...
        explicit_mask, ...
        mask_cache_directory ...
    );

    prepared_explicit_mask = add_volume_index( ...
        prepared_mask_path ...
    );
end

%% ========================================================================
% 4. Detect ROI directories
% ========================================================================

roi_directories = detect_roi_directories( ...
    first_level_root, ...
    second_level_root ...
);

if isempty(roi_directories)
    error( ...
        'No ROI directories were found under:\n%s', ...
        first_level_root ...
    );
end

fprintf( ...
    '\nDetected %d ROI directories.\n', ...
    numel(roi_directories) ...
);

%% ========================================================================
% 5. Run all ROI-by-phase models
% ========================================================================

summary_rows = {};

for roi_index = 1:numel(roi_directories)

    roi_name = roi_directories(roi_index).name;

    roi_path = fullfile( ...
        first_level_root, ...
        roi_name ...
    );

    fprintf('\n============================================================\n');

    fprintf( ...
        'Processing ROI %d/%d: %s\n', ...
        roi_index, ...
        numel(roi_directories), ...
        roi_name ...
    );

    fprintf('============================================================\n');

    subject_directories = detect_subject_directories( ...
        roi_path ...
    );

    if isempty(subject_directories)

        fprintf( ...
            'No participant directories were found under %s.\n', ...
            roi_path ...
        );

        for phase_index = 1:numel(phases)

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                phases{phase_index}, ...
                0, ...
                'skipped', ...
                'No participant directories found' ...
            }; %#ok<AGROW>
        end

        continue;
    end

    for phase_index = 1:numel(phases)

        phase = phases{phase_index};

        fprintf('\n----------------------------------------\n');

        fprintf( ...
            'ROI: %s | Phase: %s\n', ...
            roi_name, ...
            phase ...
        );

        fprintf('----------------------------------------\n');

        output_directory = fullfile( ...
            second_level_root, ...
            roi_name, ...
            phase ...
        );

        phase_cache_root = fullfile( ...
            input_cache_root, ...
            roi_name, ...
            phase ...
        );

        scans = {};
        included_subjects = {};
        source_files = {};

        %% ----------------------------------------------------------------
        % 5.1 Collect participant-level slope maps
        % -----------------------------------------------------------------

        for subject_index = 1:numel(subject_directories)

            subject_name = ...
                subject_directories(subject_index).name;

            subject_path = fullfile( ...
                roi_path, ...
                subject_name ...
            );

            source_file = find_slope_map( ...
                subject_path, ...
                subject_name, ...
                roi_name, ...
                phase ...
            );

            if isempty(source_file)

                expected_name = sprintf( ...
                    '%s_%s_regBeta_GMresid_%s.nii', ...
                    subject_name, ...
                    roi_name, ...
                    phase ...
                );

                fprintf( ...
                    '[Missing] %s\n', ...
                    fullfile( ...
                        subject_path, ...
                        expected_name ...
                    ) ...
                );

                continue;
            end

            subject_cache_directory = fullfile( ...
                phase_cache_root, ...
                subject_name ...
            );

            try
                prepared_file = prepare_spm_nifti( ...
                    source_file, ...
                    subject_cache_directory ...
                );

            catch preparation_error

                fprintf( ...
                    '[Skipped] Could not prepare %s: %s\n', ...
                    source_file, ...
                    preparation_error.message ...
                );

                continue;
            end

            scans{end + 1, 1} = ...
                add_volume_index(prepared_file); %#ok<AGROW>

            included_subjects{end + 1, 1} = ...
                subject_name; %#ok<AGROW>

            source_files{end + 1, 1} = ...
                source_file; %#ok<AGROW>
        end

        number_of_scans = numel(scans);

        fprintf( ...
            'Participant maps found: %d\n', ...
            number_of_scans ...
        );

        if number_of_scans < minimum_scans

            reason = sprintf( ...
                'Too few participant maps (%d < %d)', ...
                number_of_scans, ...
                minimum_scans ...
            );

            fprintf( ...
                '[Skipped] %s\n', ...
                reason ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                phase, ...
                number_of_scans, ...
                'skipped', ...
                reason ...
            }; %#ok<AGROW>

            continue;
        end

        %% ----------------------------------------------------------------
        % 5.2 Validate image grids
        % -----------------------------------------------------------------

        try
            validate_scan_grids( ...
                scans, ...
                prepared_explicit_mask, ...
                affine_tolerance ...
            );

        catch grid_error

            fprintf( ...
                '[Failed] Image-grid validation failed: %s\n', ...
                grid_error.message ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                phase, ...
                number_of_scans, ...
                'failed', ...
                grid_error.message ...
            }; %#ok<AGROW>

            continue;
        end

        %% ----------------------------------------------------------------
        % 5.3 Prepare the second-level output directory
        % -----------------------------------------------------------------

        try
            prepare_output_directory( ...
                output_directory, ...
                overwrite_existing ...
            );

        catch output_error

            fprintf( ...
                '[Failed] %s\n', ...
                output_error.message ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                phase, ...
                number_of_scans, ...
                'failed', ...
                output_error.message ...
            }; %#ok<AGROW>

            continue;
        end

        %% ----------------------------------------------------------------
        % 5.4 Specify the one-sample t-test
        % -----------------------------------------------------------------

        matlabbatch = {};

        matlabbatch{1}.spm.stats.factorial_design.dir = {
            output_directory
        };

        matlabbatch{1}.spm.stats.factorial_design ...
            .des.t1.scans = scans;

        matlabbatch{1}.spm.stats.factorial_design.cov = ...
            struct( ...
                'c', {}, ...
                'cname', {}, ...
                'iCFI', {}, ...
                'iCC', {} ...
            );

        matlabbatch{1}.spm.stats.factorial_design.multi_cov = ...
            struct( ...
                'files', {}, ...
                'iCFI', {}, ...
                'iCC', {} ...
            );

        % No threshold masking.
        matlabbatch{1}.spm.stats.factorial_design ...
            .masking.tm.tm_none = 1;

        % Use SPM implicit masking.
        matlabbatch{1}.spm.stats.factorial_design ...
            .masking.im = 1;

        if isempty(prepared_explicit_mask)

            matlabbatch{1}.spm.stats.factorial_design ...
                .masking.em = {''};

        else
            matlabbatch{1}.spm.stats.factorial_design ...
                .masking.em = {
                    prepared_explicit_mask
                };
        end

        % Do not calculate or scale global values.
        matlabbatch{1}.spm.stats.factorial_design ...
            .globalc.g_omit = 1;

        matlabbatch{1}.spm.stats.factorial_design ...
            .globalm.gmsca.gmsca_no = 1;

        matlabbatch{1}.spm.stats.factorial_design ...
            .globalm.glonorm = 1;

        %% ----------------------------------------------------------------
        % 5.5 Estimate the group-level model
        % -----------------------------------------------------------------

        spm_mat_path = fullfile( ...
            output_directory, ...
            'SPM.mat' ...
        );

        matlabbatch{2}.spm.stats.fmri_est.spmmat = {
            spm_mat_path
        };

        matlabbatch{2}.spm.stats.fmri_est ...
            .write_residuals = 0;

        matlabbatch{2}.spm.stats.fmri_est ...
            .method.Classical = 1;

        %% ----------------------------------------------------------------
        % 5.6 Define positive and negative slope contrasts
        % -----------------------------------------------------------------

        matlabbatch{3}.spm.stats.con.spmmat = {
            spm_mat_path
        };

        matlabbatch{3}.spm.stats.con.consess{1} ...
            .tcon.name = [
                phase, ...
                '_pos'
            ];

        matlabbatch{3}.spm.stats.con.consess{1} ...
            .tcon.weights = 1;

        matlabbatch{3}.spm.stats.con.consess{1} ...
            .tcon.sessrep = 'none';

        matlabbatch{3}.spm.stats.con.consess{2} ...
            .tcon.name = [
                phase, ...
                '_neg'
            ];

        matlabbatch{3}.spm.stats.con.consess{2} ...
            .tcon.weights = -1;

        matlabbatch{3}.spm.stats.con.consess{2} ...
            .tcon.sessrep = 'none';

        matlabbatch{3}.spm.stats.con.delete = 1;

        %% ----------------------------------------------------------------
        % 5.7 Run the SPM batch
        % -----------------------------------------------------------------

        try
            spm_jobman( ...
                'run', ...
                matlabbatch ...
            );

            write_subject_manifest( ...
                output_directory, ...
                included_subjects ...
            );

            fprintf( ...
                '[Completed] ROI=%s, Phase=%s, N=%d\n', ...
                roi_name, ...
                phase, ...
                number_of_scans ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                phase, ...
                number_of_scans, ...
                'completed', ...
                '' ...
            }; %#ok<AGROW>

        catch analysis_error

            fprintf( ...
                '[Failed] ROI=%s, Phase=%s\n', ...
                roi_name, ...
                phase ...
            );

            fprintf( ...
                '%s\n', ...
                analysis_error.message ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                phase, ...
                number_of_scans, ...
                'failed', ...
                analysis_error.message ...
            }; %#ok<AGROW>
        end
    end
end

%% ========================================================================
% 6. Save batch-level processing summary
% ========================================================================

summary_path = write_processing_summary( ...
    second_level_root, ...
    summary_rows ...
);

number_completed = sum( ...
    strcmp( ...
        summary_rows(:, 4), ...
        'completed' ...
    ) ...
);

number_failed = sum( ...
    strcmp( ...
        summary_rows(:, 4), ...
        'failed' ...
    ) ...
);

number_skipped = sum( ...
    strcmp( ...
        summary_rows(:, 4), ...
        'skipped' ...
    ) ...
);

fprintf('\n============================================================\n');
fprintf('Second-level analyses finished\n');
fprintf('============================================================\n');

fprintf( ...
    'Completed models: %d\n', ...
    number_completed ...
);

fprintf( ...
    'Failed models:    %d\n', ...
    number_failed ...
);

fprintf( ...
    'Skipped models:   %d\n', ...
    number_skipped ...
);

fprintf( ...
    'Summary file:     %s\n', ...
    summary_path ...
);

fprintf( ...
    'Output root:      %s\n', ...
    second_level_root ...
);

fprintf('============================================================\n');

end


%% ========================================================================
% Local helper functions
% ========================================================================

function phases = normalize_phase_list(input_phases)
% Normalize phase names to uppercase cell strings.

if ischar(input_phases) || isstring(input_phases)
    input_phases = cellstr(input_phases);
end

phases = {};

for index = 1:numel(input_phases)

    phase = upper( ...
        strtrim( ...
            char(input_phases{index}) ...
        ) ...
    );

    if isempty(phase)
        continue;
    end

    if ~ismember(phase, phases)
        phases{end + 1} = phase; %#ok<AGROW>
    end
end

if isempty(phases)
    error( ...
        'At least one phase must be provided.' ...
    );
end

end


function roi_directories = detect_roi_directories( ...
    first_level_root, ...
    second_level_root ...
)
% Detect ROI directories under the first-level root.

all_directories = dir( ...
    first_level_root ...
);

all_directories = all_directories( ...
    [all_directories.isdir] ...
);

keep = true( ...
    numel(all_directories), ...
    1 ...
);

second_level_canonical = canonical_path( ...
    second_level_root ...
);

for index = 1:numel(all_directories)

    name = all_directories(index).name;

    if ...
            strcmp(name, '.') ...
            || strcmp(name, '..') ...
            || startsWith(name, '.')

        keep(index) = false;
        continue;
    end

    current_path = fullfile( ...
        first_level_root, ...
        name ...
    );

    if strcmp( ...
            canonical_path(current_path), ...
            second_level_canonical ...
        )

        keep(index) = false;
    end
end

roi_directories = all_directories(keep);

roi_directories = natural_sort_directory_struct( ...
    roi_directories ...
);

end


function subject_directories = detect_subject_directories(roi_path)
% Detect participant directories matching Sub<number>.

all_directories = dir( ...
    fullfile( ...
        roi_path, ...
        'Sub*' ...
    ) ...
);

all_directories = all_directories( ...
    [all_directories.isdir] ...
);

keep = false( ...
    numel(all_directories), ...
    1 ...
);

for index = 1:numel(all_directories)

    keep(index) = ~isempty( ...
        regexp( ...
            all_directories(index).name, ...
            '^Sub\d+$', ...
            'once' ...
        ) ...
    );
end

subject_directories = all_directories(keep);

subject_directories = natural_sort_directory_struct( ...
    subject_directories ...
);

end


function slope_file = find_slope_map( ...
    subject_path, ...
    subject_name, ...
    roi_name, ...
    phase ...
)
% Locate an uncompressed or compressed first-level slope map.

base_name = sprintf( ...
    '%s_%s_regBeta_GMresid_%s', ...
    subject_name, ...
    roi_name, ...
    phase ...
);

candidates = {
    fullfile( ...
        subject_path, ...
        [base_name, '.nii'] ...
    ), ...
    fullfile( ...
        subject_path, ...
        [base_name, '.nii.gz'] ...
    ) ...
};

slope_file = '';

for index = 1:numel(candidates)

    if exist(candidates{index}, 'file') == 2

        slope_file = candidates{index};
        return;
    end
end

end


function prepared_path = prepare_spm_nifti( ...
    input_path, ...
    cache_directory ...
)
% Return an uncompressed NIfTI path suitable for SPM.
%
% An input .nii file is returned directly. An input .nii.gz file is
% decompressed into the specified cache directory.

input_path = char(input_path);

if exist(input_path, 'file') ~= 2
    error( ...
        'Input image does not exist: %s', ...
        input_path ...
    );
end

if endsWith( ...
        lower(input_path), ...
        '.nii' ...
    )

    prepared_path = input_path;
    return;
end

if ~endsWith( ...
        lower(input_path), ...
        '.nii.gz' ...
    )

    error( ...
        'Unsupported image extension: %s', ...
        input_path ...
    );
end

if exist(cache_directory, 'dir') ~= 7
    mkdir(cache_directory);
end

output_name = [
    strip_nifti_suffix(input_path), ...
    '.nii' ...
];

prepared_path = fullfile( ...
    cache_directory, ...
    output_name ...
);

source_info = dir( ...
    input_path ...
);

target_info = dir( ...
    prepared_path ...
);

needs_extraction = ...
    isempty(target_info) ...
    || target_info.datenum < source_info.datenum;

if needs_extraction

    if exist(prepared_path, 'file') == 2
        delete(prepared_path);
    end

    extracted_files = gunzip( ...
        input_path, ...
        cache_directory ...
    );

    if isempty(extracted_files)
        error( ...
            'Failed to decompress NIfTI file: %s', ...
            input_path ...
        );
    end
end

if exist(prepared_path, 'file') ~= 2
    error( ...
        'Decompressed NIfTI file was not created: %s', ...
        prepared_path ...
    );
end

end


function indexed_path = add_volume_index(file_path)
% Add the SPM volume suffix ",1" when it is not already present.

file_path = char(file_path);

if isempty( ...
        regexp( ...
            file_path, ...
            ',\d+$', ...
            'once' ...
        ) ...
    )

    indexed_path = [
        file_path, ...
        ',1' ...
    ];

else
    indexed_path = file_path;
end

end


function clean_path = remove_volume_index(indexed_path)
% Remove a trailing SPM volume suffix such as ",1".

clean_path = regexprep( ...
    char(indexed_path), ...
    ',\d+$', ...
    '' ...
);

end


function validate_scan_grids( ...
    scans, ...
    explicit_mask, ...
    affine_tolerance ...
)
% Verify that all participant maps share dimensions and affine matrices.

reference_path = remove_volume_index( ...
    scans{1} ...
);

reference_volume = spm_vol( ...
    reference_path ...
);

reference_dimensions = ...
    reference_volume(1).dim;

reference_affine = ...
    reference_volume(1).mat;

for index = 1:numel(scans)

    current_path = remove_volume_index( ...
        scans{index} ...
    );

    current_volume = spm_vol( ...
        current_path ...
    );

    if ~isequal( ...
            current_volume(1).dim, ...
            reference_dimensions ...
        )

        error( ...
            ['Image dimensions do not match the reference image.\n', ...
             'Reference: %s\nCurrent: %s'], ...
            reference_path, ...
            current_path ...
        );
    end

    maximum_affine_difference = max( ...
        abs( ...
            current_volume(1).mat(:) ...
            - reference_affine(:) ...
        ) ...
    );

    if maximum_affine_difference > affine_tolerance

        error( ...
            ['Image affine does not match the reference image.\n', ...
             'Reference: %s\nCurrent: %s\n', ...
             'Maximum difference: %.8g'], ...
            reference_path, ...
            current_path, ...
            maximum_affine_difference ...
        );
    end
end

if ~isempty(explicit_mask)

    mask_path = remove_volume_index( ...
        explicit_mask ...
    );

    mask_volume = spm_vol( ...
        mask_path ...
    );

    if ~isequal( ...
            mask_volume(1).dim, ...
            reference_dimensions ...
        )

        error( ...
            ['Explicit-mask dimensions do not match the input maps.\n', ...
             'Mask: %s\nReference: %s'], ...
            mask_path, ...
            reference_path ...
        );
    end

    maximum_mask_affine_difference = max( ...
        abs( ...
            mask_volume(1).mat(:) ...
            - reference_affine(:) ...
        ) ...
    );

    if maximum_mask_affine_difference > affine_tolerance

        error( ...
            ['Explicit-mask affine does not match the input maps.\n', ...
             'Mask: %s\nReference: %s\n', ...
             'Maximum difference: %.8g'], ...
            mask_path, ...
            reference_path, ...
            maximum_mask_affine_difference ...
        );
    end
end

end


function prepare_output_directory( ...
    output_directory, ...
    overwrite_existing ...
)
% Create the output directory and safely remove an existing SPM model.
%
% Only known SPM model files are removed. Other files and subdirectories
% are preserved.

if exist(output_directory, 'dir') ~= 7
    mkdir(output_directory);
    return;
end

existing_spm = fullfile( ...
    output_directory, ...
    'SPM.mat' ...
);

if exist(existing_spm, 'file') ~= 2
    return;
end

if ~overwrite_existing

    error( ...
        ['An existing SPM model was found in:\n%s\n', ...
         'Set overwrite_existing=true to replace it.'], ...
        output_directory ...
    );
end

patterns_to_remove = {
    'SPM.mat', ...
    'mask.nii', ...
    'mask.nii.gz', ...
    'ResMS.nii', ...
    'ResMS.nii.gz', ...
    'RPV.nii', ...
    'RPV.nii.gz', ...
    'beta_*.nii', ...
    'beta_*.nii.gz', ...
    'con_*.nii', ...
    'con_*.nii.gz', ...
    'ess_*.nii', ...
    'ess_*.nii.gz', ...
    'spmT_*.nii', ...
    'spmT_*.nii.gz', ...
    'spmF_*.nii', ...
    'spmF_*.nii.gz', ...
    'ResI_*.nii', ...
    'ResI_*.nii.gz' ...
};

for pattern_index = 1:numel(patterns_to_remove)

    matching_files = dir( ...
        fullfile( ...
            output_directory, ...
            patterns_to_remove{pattern_index} ...
        ) ...
    );

    for file_index = 1:numel(matching_files)

        file_path = fullfile( ...
            output_directory, ...
            matching_files(file_index).name ...
        );

        if exist(file_path, 'file') == 2
            delete(file_path);
        end
    end
end

end


function write_subject_manifest( ...
    output_directory, ...
    subject_names ...
)
% Save the participant IDs included in a second-level model.

manifest_path = fullfile( ...
    output_directory, ...
    'included_subjects.txt' ...
);

file_id = fopen( ...
    manifest_path, ...
    'w' ...
);

if file_id == -1
    warning( ...
        'Could not create participant manifest: %s', ...
        manifest_path ...
    );
    return;
end

for index = 1:numel(subject_names)

    fprintf( ...
        file_id, ...
        '%s\n', ...
        subject_names{index} ...
    );
end

fclose(file_id);

end


function summary_path = write_processing_summary( ...
    second_level_root, ...
    summary_rows ...
)
% Write a TSV summary of all requested second-level models.

summary_path = fullfile( ...
    second_level_root, ...
    'second_level_summary.tsv' ...
);

file_id = fopen( ...
    summary_path, ...
    'w' ...
);

if file_id == -1
    error( ...
        'Could not create processing summary: %s', ...
        summary_path ...
    );
end

fprintf( ...
    file_id, ...
    'roi\tphase\tn_scans\tstatus\treason\n' ...
);

for row_index = 1:size(summary_rows, 1)

    fprintf( ...
        file_id, ...
        '%s\t%s\t%d\t%s\t%s\n', ...
        clean_tsv_field(summary_rows{row_index, 1}), ...
        clean_tsv_field(summary_rows{row_index, 2}), ...
        summary_rows{row_index, 3}, ...
        clean_tsv_field(summary_rows{row_index, 4}), ...
        clean_tsv_field(summary_rows{row_index, 5}) ...
    );
end

fclose(file_id);

end


function value = clean_tsv_field(value)
% Remove tabs and line breaks before writing a TSV field.

value = char( ...
    string(value) ...
);

value = strrep( ...
    value, ...
    sprintf('\t'), ...
    ' ' ...
);

value = strrep( ...
    value, ...
    sprintf('\r'), ...
    ' ' ...
);

value = strrep( ...
    value, ...
    sprintf('\n'), ...
    ' ' ...
);

end


function sorted_directories = natural_sort_directory_struct( ...
    directory_struct ...
)
% Sort directories by the numeric component of their names.

if isempty(directory_struct)
    sorted_directories = directory_struct;
    return;
end

numeric_values = nan( ...
    numel(directory_struct), ...
    1 ...
);

for index = 1:numel(directory_struct)

    token = regexp( ...
        directory_struct(index).name, ...
        '\d+', ...
        'match', ...
        'once' ...
    );

    if ~isempty(token)
        numeric_values(index) = str2double(token);
    end
end

alphabetical_names = lower( ...
    string( ...
        {directory_struct.name} ...
    ) ...
);

sorting_table = table( ...
    isnan(numeric_values), ...
    numeric_values, ...
    alphabetical_names(:), ...
    (1:numel(directory_struct))', ...
    'VariableNames', ...
    { ...
        'MissingNumber', ...
        'Number', ...
        'Name', ...
        'OriginalIndex' ...
    } ...
);

sorting_table = sortrows( ...
    sorting_table, ...
    { ...
        'MissingNumber', ...
        'Number', ...
        'Name' ...
    } ...
);

sorted_directories = directory_struct( ...
    sorting_table.OriginalIndex ...
);

end


function name = strip_nifti_suffix(file_path)
% Return the filename without .nii or .nii.gz.

[~, name, extension] = fileparts( ...
    file_path ...
);

if strcmpi(extension, '.gz')

    [~, name] = fileparts( ...
        name ...
    );
end

end


function output = canonical_path(input_path)
% Return a normalized absolute path for path comparison.

input_file = java.io.File( ...
    input_path ...
);

output = char( ...
    input_file.getCanonicalPath() ...
);

end