function run_second_level_paired_tests(varargin)
% =========================================================================
% SPM12 second-level paired-samples t-tests for first-level slope maps
%
% For each ROI, this script performs all pairwise comparisons among the
% requested learning-stage labels.
%
% Each comparison produces two directional contrasts:
%
%   1. Condition A > Condition B: [1 -1]
%   2. Condition B > Condition A: [-1 1]
%
% -------------------------------------------------------------------------
% Expected input structure
% -------------------------------------------------------------------------
%
% <first_level_root>/
% ├── ROI_1/
% │   ├── Sub02/
% │   │   ├── Sub02_ROI_1_regBeta_GMresid_LE.nii
% │   │   └── Sub02_ROI_1_regBeta_GMresid_RN.nii
% │   ├── Sub03/
% │   │   └── ...
% │   └── ...
% ├── ROI_2/
% │   └── ...
% └── ...
%
% Both .nii and .nii.gz input files are supported.
%
% -------------------------------------------------------------------------
% Output structure
% -------------------------------------------------------------------------
%
% <second_level_root>/
% ├── ROI_1/
% │   ├── LE_vs_RN/
% │   │   ├── SPM.mat
% │   │   ├── con_0001.nii
% │   │   ├── con_0002.nii
% │   │   ├── spmT_0001.nii
% │   │   ├── spmT_0002.nii
% │   │   ├── included_subjects.txt
% │   │   └── batch_paired_t.mat
% │   └── ...
% ├── ROI_2/
% │   └── ...
% ├── _spm_input_cache/
% └── paired_second_level_summary.tsv
%
% -------------------------------------------------------------------------
% Default paths
% -------------------------------------------------------------------------
%
% Paths are resolved relative to the location of this MATLAB file:
%
%   First-level input:
%       outputs/roi_pattern_regression/
%
%   Paired second-level output:
%       outputs/roi_pattern_regression_second_level_paired/
%
% -------------------------------------------------------------------------
% Example
% -------------------------------------------------------------------------
%
% run_second_level_paired_tests( ...
%     'first_level_root', '/path/to/first_level_maps', ...
%     'second_level_root', '/path/to/paired_results', ...
%     'explicit_mask', '/path/to/group_mask.nii', ...
%     'labels', {'LE', 'RN'});
%
% Analyze all four learning stages:
%
% run_second_level_paired_tests( ...
%     'labels', {'LN', 'LE', 'RN', 'RE'});
%
% Prevent replacement of existing SPM models:
%
% run_second_level_paired_tests( ...
%     'overwrite_existing', false);
%
% -------------------------------------------------------------------------
% Notes
% -------------------------------------------------------------------------
%
% - Only participants with both maps in a comparison are included.
% - Compressed NIfTI files are decompressed into an internal cache before
%   they are passed to SPM.
% - Existing output directories are cleaned selectively. The script does
%   not recursively delete unrelated files or subdirectories.
% - At least two complete participant pairs are required by default.
%
% Dependency
% ----------
% SPM12
% =========================================================================

clc;

%% ========================================================================
% 0. Parse input settings
% ========================================================================

script_path = mfilename('fullpath');
script_dir = fileparts(script_path);

default_first_level_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'roi_pattern_regression' ...
);

default_second_level_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'roi_pattern_regression_second_level_paired' ...
);

parser = inputParser;

addParameter( ...
    parser, ...
    'first_level_root', ...
    default_first_level_root, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'second_level_root', ...
    default_second_level_root, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'explicit_mask', ...
    '', ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'labels', ...
    {'LE', 'RN'}, ...
    @(x) iscell(x) || ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'minimum_pairs', ...
    2, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 2 ...
);

addParameter( ...
    parser, ...
    'overwrite_existing', ...
    true, ...
    @(x) islogical(x) && isscalar(x) ...
);

addParameter( ...
    parser, ...
    'affine_tolerance', ...
    1e-4, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0 ...
);

parse(parser, varargin{:});

first_level_root = char( ...
    parser.Results.first_level_root ...
);

second_level_root = char( ...
    parser.Results.second_level_root ...
);

explicit_mask = char( ...
    parser.Results.explicit_mask ...
);

labels = normalize_label_list( ...
    parser.Results.labels ...
);

minimum_pairs = parser.Results.minimum_pairs;

overwrite_existing = ...
    parser.Results.overwrite_existing;

affine_tolerance = ...
    parser.Results.affine_tolerance;

if numel(labels) < 2
    error( ...
        'At least two labels are required for paired comparisons.' ...
    );
end

label_pairs = nchoosek( ...
    1:numel(labels), ...
    2 ...
);

%% ========================================================================
% 1. Validate software and paths
% ========================================================================

if exist('spm', 'file') ~= 2
    error( ...
        ['SPM12 was not found on the MATLAB path. ', ...
         'Install SPM12 and add it to the MATLAB path.'] ...
    );
end

if exist(first_level_root, 'dir') ~= 7
    error( ...
        'First-level root directory does not exist:\n%s', ...
        first_level_root ...
    );
end

if exist(second_level_root, 'dir') ~= 7
    mkdir(second_level_root);
end

if ...
        ~isempty(explicit_mask) ...
        && exist(explicit_mask, 'file') ~= 2

    error( ...
        'Explicit mask does not exist:\n%s', ...
        explicit_mask ...
    );
end

input_cache_root = fullfile( ...
    second_level_root, ...
    '_spm_input_cache' ...
);

if exist(input_cache_root, 'dir') ~= 7
    mkdir(input_cache_root);
end

fprintf('\n============================================================\n');
fprintf('SPM12 second-level paired-samples t-tests\n');
fprintf('============================================================\n');

fprintf( ...
    'First-level root:    %s\n', ...
    first_level_root ...
);

fprintf( ...
    'Second-level root:   %s\n', ...
    second_level_root ...
);

fprintf( ...
    'Labels:              %s\n', ...
    strjoin(labels, ', ') ...
);

fprintf( ...
    'Pairwise models:     %d\n', ...
    size(label_pairs, 1) ...
);

fprintf( ...
    'Minimum pairs:       %d\n', ...
    minimum_pairs ...
);

fprintf( ...
    'Overwrite existing:  %d\n', ...
    overwrite_existing ...
);

if isempty(explicit_mask)
    fprintf('Explicit mask:       none\n');
else
    fprintf( ...
        'Explicit mask:       %s\n', ...
        explicit_mask ...
    );
end

fprintf('============================================================\n');

%% ========================================================================
% 2. Initialize SPM
% ========================================================================

spm('Defaults', 'fMRI');
spm_jobman('initcfg');

%% ========================================================================
% 3. Prepare the optional explicit mask
% ========================================================================

if isempty(explicit_mask)

    prepared_explicit_mask = '';

else
    mask_cache_directory = fullfile( ...
        input_cache_root, ...
        'explicit_mask' ...
    );

    prepared_mask_path = prepare_spm_nifti( ...
        explicit_mask, ...
        mask_cache_directory ...
    );

    prepared_explicit_mask = add_volume_index( ...
        prepared_mask_path ...
    );
end

%% ========================================================================
% 4. Detect ROI directories
% ========================================================================

roi_directories = detect_roi_directories( ...
    first_level_root, ...
    second_level_root ...
);

if isempty(roi_directories)
    error( ...
        'No ROI directories were found under:\n%s', ...
        first_level_root ...
    );
end

fprintf( ...
    '\nDetected %d ROI directories.\n', ...
    numel(roi_directories) ...
);

%% ========================================================================
% 5. Run all ROI-by-label-pair models
% ========================================================================

summary_rows = {};

for roi_index = 1:numel(roi_directories)

    roi_name = roi_directories(roi_index).name;

    roi_path = fullfile( ...
        first_level_root, ...
        roi_name ...
    );

    fprintf('\n============================================================\n');

    fprintf( ...
        'Processing ROI %d/%d: %s\n', ...
        roi_index, ...
        numel(roi_directories), ...
        roi_name ...
    );

    fprintf('============================================================\n');

    subject_directories = detect_subject_directories( ...
        roi_path ...
    );

    if isempty(subject_directories)

        fprintf( ...
            'No participant directories were found under %s.\n', ...
            roi_path ...
        );

        for pair_index = 1:size(label_pairs, 1)

            label_a = labels{label_pairs(pair_index, 1)};
            label_b = labels{label_pairs(pair_index, 2)};

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                label_a, ...
                label_b, ...
                0, ...
                'skipped', ...
                'No participant directories found' ...
            }; %#ok<AGROW>
        end

        continue;
    end

    %% --------------------------------------------------------------------
    % Run each requested pairwise comparison
    % ---------------------------------------------------------------------

    for pair_index = 1:size(label_pairs, 1)

        label_a = labels{ ...
            label_pairs(pair_index, 1) ...
        };

        label_b = labels{ ...
            label_pairs(pair_index, 2) ...
        };

        comparison_name = sprintf( ...
            '%s_vs_%s', ...
            label_a, ...
            label_b ...
        );

        fprintf('\n----------------------------------------\n');

        fprintf( ...
            'ROI: %s | Comparison: %s vs %s\n', ...
            roi_name, ...
            label_a, ...
            label_b ...
        );

        fprintf('----------------------------------------\n');

        output_directory = fullfile( ...
            second_level_root, ...
            roi_name, ...
            comparison_name ...
        );

        comparison_cache_root = fullfile( ...
            input_cache_root, ...
            roi_name, ...
            comparison_name ...
        );

        pair_scans = struct( ...
            'scans', {} ...
        );

        included_subjects = {};

        %% ----------------------------------------------------------------
        % 5.1 Collect complete participant pairs
        % -----------------------------------------------------------------

        number_of_pairs = 0;

        for subject_index = 1:numel(subject_directories)

            subject_name = ...
                subject_directories(subject_index).name;

            subject_path = fullfile( ...
                roi_path, ...
                subject_name ...
            );

            source_file_a = find_slope_map( ...
                subject_path, ...
                subject_name, ...
                roi_name, ...
                label_a ...
            );

            source_file_b = find_slope_map( ...
                subject_path, ...
                subject_name, ...
                roi_name, ...
                label_b ...
            );

            if isempty(source_file_a)

                expected_name_a = sprintf( ...
                    '%s_%s_regBeta_GMresid_%s.nii', ...
                    subject_name, ...
                    roi_name, ...
                    label_a ...
                );

                fprintf( ...
                    '[Missing %s] %s\n', ...
                    label_a, ...
                    fullfile( ...
                        subject_path, ...
                        expected_name_a ...
                    ) ...
                );
            end

            if isempty(source_file_b)

                expected_name_b = sprintf( ...
                    '%s_%s_regBeta_GMresid_%s.nii', ...
                    subject_name, ...
                    roi_name, ...
                    label_b ...
                );

                fprintf( ...
                    '[Missing %s] %s\n', ...
                    label_b, ...
                    fullfile( ...
                        subject_path, ...
                        expected_name_b ...
                    ) ...
                );
            end

            if ...
                    isempty(source_file_a) ...
                    || isempty(source_file_b)

                continue;
            end

            subject_cache_directory = fullfile( ...
                comparison_cache_root, ...
                subject_name ...
            );

            try
                prepared_file_a = prepare_spm_nifti( ...
                    source_file_a, ...
                    subject_cache_directory ...
                );

                prepared_file_b = prepare_spm_nifti( ...
                    source_file_b, ...
                    subject_cache_directory ...
                );

            catch preparation_error

                fprintf( ...
                    '[Skipped] Could not prepare inputs for %s: %s\n', ...
                    subject_name, ...
                    preparation_error.message ...
                );

                continue;
            end

            number_of_pairs = number_of_pairs + 1;

            pair_scans(number_of_pairs).scans = { ...
                add_volume_index(prepared_file_a)
                add_volume_index(prepared_file_b)
            };

            included_subjects{number_of_pairs, 1} = ...
                subject_name; %#ok<AGROW>
        end

        fprintf( ...
            'Complete participant pairs: %d\n', ...
            number_of_pairs ...
        );

        if number_of_pairs < minimum_pairs

            reason = sprintf( ...
                'Too few complete participant pairs (%d < %d)', ...
                number_of_pairs, ...
                minimum_pairs ...
            );

            fprintf( ...
                '[Skipped] %s\n', ...
                reason ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                label_a, ...
                label_b, ...
                number_of_pairs, ...
                'skipped', ...
                reason ...
            }; %#ok<AGROW>

            continue;
        end

        %% ----------------------------------------------------------------
        % 5.2 Validate image grids
        % -----------------------------------------------------------------

        try
            validate_paired_scan_grids( ...
                pair_scans, ...
                prepared_explicit_mask, ...
                affine_tolerance ...
            );

        catch grid_error

            fprintf( ...
                '[Failed] Image-grid validation failed: %s\n', ...
                grid_error.message ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                label_a, ...
                label_b, ...
                number_of_pairs, ...
                'failed', ...
                grid_error.message ...
            }; %#ok<AGROW>

            continue;
        end

        %% ----------------------------------------------------------------
        % 5.3 Prepare the output directory
        % -----------------------------------------------------------------

        try
            prepare_output_directory( ...
                output_directory, ...
                overwrite_existing ...
            );

        catch output_error

            fprintf( ...
                '[Failed] %s\n', ...
                output_error.message ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                label_a, ...
                label_b, ...
                number_of_pairs, ...
                'failed', ...
                output_error.message ...
            }; %#ok<AGROW>

            continue;
        end

        %% ----------------------------------------------------------------
        % 5.4 Specify the paired-samples t-test
        % -----------------------------------------------------------------

        matlabbatch = {};

        matlabbatch{1}.spm.stats.factorial_design.dir = {
            output_directory
        };

        matlabbatch{1}.spm.stats.factorial_design ...
            .des.pt.pair = struct( ...
                'scans', {} ...
            );

        for subject_index = 1:number_of_pairs

            matlabbatch{1}.spm.stats.factorial_design ...
                .des.pt.pair(subject_index).scans = ...
                pair_scans(subject_index).scans;
        end

        % Disable grand-mean scaling and ANCOVA within the paired design.
        matlabbatch{1}.spm.stats.factorial_design ...
            .des.pt.gmsca = 0;

        matlabbatch{1}.spm.stats.factorial_design ...
            .des.pt.ancova = 0;

        % No covariates are included.
        matlabbatch{1}.spm.stats.factorial_design.cov = ...
            struct( ...
                'c', {}, ...
                'cname', {}, ...
                'iCFI', {}, ...
                'iCC', {} ...
            );

        matlabbatch{1}.spm.stats.factorial_design.multi_cov = ...
            struct( ...
                'files', {}, ...
                'iCFI', {}, ...
                'iCC', {} ...
            );

        % Disable threshold masking.
        matlabbatch{1}.spm.stats.factorial_design ...
            .masking.tm.tm_none = 1;

        % Enable implicit masking.
        matlabbatch{1}.spm.stats.factorial_design ...
            .masking.im = 1;

        if isempty(prepared_explicit_mask)

            matlabbatch{1}.spm.stats.factorial_design ...
                .masking.em = {''};

        else
            matlabbatch{1}.spm.stats.factorial_design ...
                .masking.em = {
                    prepared_explicit_mask
                };
        end

        % Do not calculate or normalize global values.
        matlabbatch{1}.spm.stats.factorial_design ...
            .globalc.g_omit = 1;

        matlabbatch{1}.spm.stats.factorial_design ...
            .globalm.gmsca.gmsca_no = 1;

        matlabbatch{1}.spm.stats.factorial_design ...
            .globalm.glonorm = 1;

        %% ----------------------------------------------------------------
        % 5.5 Estimate the second-level model
        % -----------------------------------------------------------------

        spm_mat_path = fullfile( ...
            output_directory, ...
            'SPM.mat' ...
        );

        matlabbatch{2}.spm.stats.fmri_est.spmmat = {
            spm_mat_path
        };

        matlabbatch{2}.spm.stats.fmri_est ...
            .write_residuals = 0;

        matlabbatch{2}.spm.stats.fmri_est ...
            .method.Classical = 1;

        %% ----------------------------------------------------------------
        % 5.6 Define directional paired contrasts
        % -----------------------------------------------------------------

        matlabbatch{3}.spm.stats.con.spmmat = {
            spm_mat_path
        };

        matlabbatch{3}.spm.stats.con.consess{1} ...
            .tcon.name = sprintf( ...
                '%s_gt_%s', ...
                label_a, ...
                label_b ...
            );

        matlabbatch{3}.spm.stats.con.consess{1} ...
            .tcon.weights = [1, -1];

        matlabbatch{3}.spm.stats.con.consess{1} ...
            .tcon.sessrep = 'none';

        matlabbatch{3}.spm.stats.con.consess{2} ...
            .tcon.name = sprintf( ...
                '%s_gt_%s', ...
                label_b, ...
                label_a ...
            );

        matlabbatch{3}.spm.stats.con.consess{2} ...
            .tcon.weights = [-1, 1];

        matlabbatch{3}.spm.stats.con.consess{2} ...
            .tcon.sessrep = 'none';

        matlabbatch{3}.spm.stats.con.delete = 1;

        %% ----------------------------------------------------------------
        % 5.7 Save and run the SPM batch
        % -----------------------------------------------------------------

        batch_path = fullfile( ...
            output_directory, ...
            'batch_paired_t.mat' ...
        );

        save( ...
            batch_path, ...
            'matlabbatch' ...
        );

        try
            spm_jobman( ...
                'run', ...
                matlabbatch ...
            );

            write_subject_manifest( ...
                output_directory, ...
                included_subjects ...
            );

            fprintf( ...
                '[Completed] ROI=%s | %s vs %s | N=%d\n', ...
                roi_name, ...
                label_a, ...
                label_b, ...
                number_of_pairs ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                label_a, ...
                label_b, ...
                number_of_pairs, ...
                'completed', ...
                '' ...
            }; %#ok<AGROW>

        catch analysis_error

            fprintf( ...
                '[Failed] ROI=%s | %s vs %s\n', ...
                roi_name, ...
                label_a, ...
                label_b ...
            );

            fprintf( ...
                '%s\n', ...
                analysis_error.message ...
            );

            summary_rows(end + 1, :) = { ...
                roi_name, ...
                label_a, ...
                label_b, ...
                number_of_pairs, ...
                'failed', ...
                analysis_error.message ...
            }; %#ok<AGROW>
        end
    end
end

%% ========================================================================
% 6. Save the batch-level processing summary
% ========================================================================

summary_path = write_processing_summary( ...
    second_level_root, ...
    summary_rows ...
);

number_completed = count_summary_status( ...
    summary_rows, ...
    'completed' ...
);

number_failed = count_summary_status( ...
    summary_rows, ...
    'failed' ...
);

number_skipped = count_summary_status( ...
    summary_rows, ...
    'skipped' ...
);

fprintf('\n============================================================\n');
fprintf('Paired second-level analyses finished\n');
fprintf('============================================================\n');

fprintf( ...
    'Completed models: %d\n', ...
    number_completed ...
);

fprintf( ...
    'Failed models:    %d\n', ...
    number_failed ...
);

fprintf( ...
    'Skipped models:   %d\n', ...
    number_skipped ...
);

fprintf( ...
    'Summary file:     %s\n', ...
    summary_path ...
);

fprintf( ...
    'Output root:      %s\n', ...
    second_level_root ...
);

fprintf('============================================================\n');

end


%% ========================================================================
% Local helper functions
% ========================================================================

function labels = normalize_label_list(input_labels)
% Normalize label names to uppercase cell strings.

if ischar(input_labels) || isstring(input_labels)
    input_labels = cellstr(input_labels);
end

labels = {};

for index = 1:numel(input_labels)

    label = upper( ...
        strtrim( ...
            char(input_labels{index}) ...
        ) ...
    );

    if isempty(label)
        continue;
    end

    if ~ismember(label, labels)
        labels{end + 1} = label; %#ok<AGROW>
    end
end

if isempty(labels)
    error( ...
        'At least one label must be provided.' ...
    );
end

end


function roi_directories = detect_roi_directories( ...
    first_level_root, ...
    second_level_root ...
)
% Detect ROI directories under the first-level root.

all_directories = dir( ...
    first_level_root ...
);

all_directories = all_directories( ...
    [all_directories.isdir] ...
);

keep = true( ...
    numel(all_directories), ...
    1 ...
);

second_level_canonical = canonical_path( ...
    second_level_root ...
);

for index = 1:numel(all_directories)

    directory_name = all_directories(index).name;

    if ...
            strcmp(directory_name, '.') ...
            || strcmp(directory_name, '..') ...
            || startsWith(directory_name, '.') ...
            || startsWith(directory_name, '_')

        keep(index) = false;
        continue;
    end

    current_path = fullfile( ...
        first_level_root, ...
        directory_name ...
    );

    if strcmp( ...
            canonical_path(current_path), ...
            second_level_canonical ...
        )

        keep(index) = false;
    end
end

roi_directories = all_directories(keep);

roi_directories = sort_directory_struct_by_name( ...
    roi_directories ...
);

end


function subject_directories = detect_subject_directories(roi_path)
% Detect participant directories matching Sub<number>.

all_directories = dir( ...
    fullfile( ...
        roi_path, ...
        'Sub*' ...
    ) ...
);

all_directories = all_directories( ...
    [all_directories.isdir] ...
);

keep = false( ...
    numel(all_directories), ...
    1 ...
);

for index = 1:numel(all_directories)

    keep(index) = ~isempty( ...
        regexp( ...
            all_directories(index).name, ...
            '^Sub\d+$', ...
            'once' ...
        ) ...
    );
end

subject_directories = all_directories(keep);

subject_directories = natural_sort_subject_directories( ...
    subject_directories ...
);

end


function slope_file = find_slope_map( ...
    subject_path, ...
    subject_name, ...
    roi_name, ...
    label ...
)
% Locate an uncompressed or compressed first-level slope map.

base_name = sprintf( ...
    '%s_%s_regBeta_GMresid_%s', ...
    subject_name, ...
    roi_name, ...
    label ...
);

candidates = {
    fullfile( ...
        subject_path, ...
        [base_name, '.nii'] ...
    ), ...
    fullfile( ...
        subject_path, ...
        [base_name, '.nii.gz'] ...
    ) ...
};

slope_file = '';

for index = 1:numel(candidates)

    if exist(candidates{index}, 'file') == 2

        slope_file = candidates{index};
        return;
    end
end

end


function prepared_path = prepare_spm_nifti( ...
    input_path, ...
    cache_directory ...
)
% Return an uncompressed NIfTI path suitable for SPM.
%
% An input .nii file is returned directly. An input .nii.gz file is
% decompressed into the specified cache directory.

input_path = char(input_path);

if exist(input_path, 'file') ~= 2
    error( ...
        'Input image does not exist: %s', ...
        input_path ...
    );
end

if endsWith( ...
        lower(input_path), ...
        '.nii' ...
    )

    prepared_path = input_path;
    return;
end

if ~endsWith( ...
        lower(input_path), ...
        '.nii.gz' ...
    )

    error( ...
        'Unsupported image extension: %s', ...
        input_path ...
    );
end

if exist(cache_directory, 'dir') ~= 7
    mkdir(cache_directory);
end

output_name = [
    strip_nifti_suffix(input_path), ...
    '.nii' ...
];

prepared_path = fullfile( ...
    cache_directory, ...
    output_name ...
);

source_information = dir( ...
    input_path ...
);

target_information = dir( ...
    prepared_path ...
);

needs_extraction = ...
    isempty(target_information) ...
    || target_information.datenum < source_information.datenum;

if needs_extraction

    if exist(prepared_path, 'file') == 2
        delete(prepared_path);
    end

    extracted_files = gunzip( ...
        input_path, ...
        cache_directory ...
    );

    if isempty(extracted_files)
        error( ...
            'Failed to decompress NIfTI file: %s', ...
            input_path ...
        );
    end
end

if exist(prepared_path, 'file') ~= 2
    error( ...
        'Decompressed NIfTI file was not created: %s', ...
        prepared_path ...
    );
end

end


function indexed_path = add_volume_index(file_path)
% Add the SPM volume suffix ",1" when it is not already present.

file_path = char(file_path);

if isempty( ...
        regexp( ...
            file_path, ...
            ',\d+$', ...
            'once' ...
        ) ...
    )

    indexed_path = [
        file_path, ...
        ',1' ...
    ];

else
    indexed_path = file_path;
end

end


function clean_path = remove_volume_index(indexed_path)
% Remove a trailing SPM volume suffix such as ",1".

clean_path = regexprep( ...
    char(indexed_path), ...
    ',\d+$', ...
    '' ...
);

end


function validate_paired_scan_grids( ...
    pair_scans, ...
    explicit_mask, ...
    affine_tolerance ...
)
% Verify that all condition maps share the same dimensions and affine.

all_scans = {};

for pair_index = 1:numel(pair_scans)

    current_pair = pair_scans(pair_index).scans;

    if numel(current_pair) ~= 2
        error( ...
            'Each paired observation must contain exactly two scans.' ...
        );
    end

    all_scans{end + 1, 1} = ...
        current_pair{1}; %#ok<AGROW>

    all_scans{end + 1, 1} = ...
        current_pair{2}; %#ok<AGROW>
end

if isempty(all_scans)
    error( ...
        'No scans were supplied for grid validation.' ...
    );
end

reference_path = remove_volume_index( ...
    all_scans{1} ...
);

reference_volume = spm_vol( ...
    reference_path ...
);

reference_dimensions = ...
    reference_volume(1).dim;

reference_affine = ...
    reference_volume(1).mat;

for index = 1:numel(all_scans)

    current_path = remove_volume_index( ...
        all_scans{index} ...
    );

    current_volume = spm_vol( ...
        current_path ...
    );

    if ~isequal( ...
            current_volume(1).dim, ...
            reference_dimensions ...
        )

        error( ...
            ['Image dimensions do not match the reference image.\n', ...
             'Reference: %s\nCurrent: %s'], ...
            reference_path, ...
            current_path ...
        );
    end

    maximum_affine_difference = max( ...
        abs( ...
            current_volume(1).mat(:) ...
            - reference_affine(:) ...
        ) ...
    );

    if maximum_affine_difference > affine_tolerance

        error( ...
            ['Image affine does not match the reference image.\n', ...
             'Reference: %s\nCurrent: %s\n', ...
             'Maximum difference: %.8g'], ...
            reference_path, ...
            current_path, ...
            maximum_affine_difference ...
        );
    end
end

if ~isempty(explicit_mask)

    mask_path = remove_volume_index( ...
        explicit_mask ...
    );

    mask_volume = spm_vol( ...
        mask_path ...
    );

    if ~isequal( ...
            mask_volume(1).dim, ...
            reference_dimensions ...
        )

        error( ...
            ['Explicit-mask dimensions do not match the input maps.\n', ...
             'Mask: %s\nReference: %s'], ...
            mask_path, ...
            reference_path ...
        );
    end

    maximum_mask_affine_difference = max( ...
        abs( ...
            mask_volume(1).mat(:) ...
            - reference_affine(:) ...
        ) ...
    );

    if maximum_mask_affine_difference > affine_tolerance

        error( ...
            ['Explicit-mask affine does not match the input maps.\n', ...
             'Mask: %s\nReference: %s\n', ...
             'Maximum difference: %.8g'], ...
            mask_path, ...
            reference_path, ...
            maximum_mask_affine_difference ...
        );
    end
end

end


function prepare_output_directory( ...
    output_directory, ...
    overwrite_existing ...
)
% Create the output directory and safely remove an existing SPM model.
%
% Only known SPM output files are removed. Unrelated files and directories
% are preserved.

if exist(output_directory, 'dir') ~= 7
    mkdir(output_directory);
    return;
end

existing_spm = fullfile( ...
    output_directory, ...
    'SPM.mat' ...
);

if exist(existing_spm, 'file') ~= 2
    return;
end

if ~overwrite_existing

    error( ...
        ['An existing SPM model was found in:\n%s\n', ...
         'Set overwrite_existing=true to replace it.'], ...
        output_directory ...
    );
end

patterns_to_remove = {
    'SPM.mat', ...
    'mask.nii', ...
    'mask.nii.gz', ...
    'ResMS.nii', ...
    'ResMS.nii.gz', ...
    'RPV.nii', ...
    'RPV.nii.gz', ...
    'beta_*.nii', ...
    'beta_*.nii.gz', ...
    'con_*.nii', ...
    'con_*.nii.gz', ...
    'ess_*.nii', ...
    'ess_*.nii.gz', ...
    'spmT_*.nii', ...
    'spmT_*.nii.gz', ...
    'spmF_*.nii', ...
    'spmF_*.nii.gz', ...
    'ResI_*.nii', ...
    'ResI_*.nii.gz', ...
    'batch_paired_t.mat', ...
    'included_subjects.txt' ...
};

for pattern_index = 1:numel(patterns_to_remove)

    matching_files = dir( ...
        fullfile( ...
            output_directory, ...
            patterns_to_remove{pattern_index} ...
        ) ...
    );

    for file_index = 1:numel(matching_files)

        file_path = fullfile( ...
            output_directory, ...
            matching_files(file_index).name ...
        );

        if exist(file_path, 'file') == 2
            delete(file_path);
        end
    end
end

end


function write_subject_manifest( ...
    output_directory, ...
    subject_names ...
)
% Save the participant IDs included in a paired second-level model.

manifest_path = fullfile( ...
    output_directory, ...
    'included_subjects.txt' ...
);

file_id = fopen( ...
    manifest_path, ...
    'w' ...
);

if file_id == -1
    warning( ...
        'Could not create participant manifest: %s', ...
        manifest_path ...
    );
    return;
end

for index = 1:numel(subject_names)

    fprintf( ...
        file_id, ...
        '%s\n', ...
        subject_names{index} ...
    );
end

fclose(file_id);

end


function summary_path = write_processing_summary( ...
    second_level_root, ...
    summary_rows ...
)
% Write a TSV summary of all requested paired models.

summary_path = fullfile( ...
    second_level_root, ...
    'paired_second_level_summary.tsv' ...
);

file_id = fopen( ...
    summary_path, ...
    'w' ...
);

if file_id == -1
    error( ...
        'Could not create processing summary: %s', ...
        summary_path ...
    );
end

fprintf( ...
    file_id, ...
    ['roi\tcondition_a\tcondition_b\t', ...
     'n_pairs\tstatus\treason\n'] ...
);

for row_index = 1:size(summary_rows, 1)

    fprintf( ...
        file_id, ...
        '%s\t%s\t%s\t%d\t%s\t%s\n', ...
        clean_tsv_field(summary_rows{row_index, 1}), ...
        clean_tsv_field(summary_rows{row_index, 2}), ...
        clean_tsv_field(summary_rows{row_index, 3}), ...
        summary_rows{row_index, 4}, ...
        clean_tsv_field(summary_rows{row_index, 5}), ...
        clean_tsv_field(summary_rows{row_index, 6}) ...
    );
end

fclose(file_id);

end


function number_of_matches = count_summary_status( ...
    summary_rows, ...
    requested_status ...
)
% Count rows with a specified processing status.

if isempty(summary_rows)

    number_of_matches = 0;
    return;
end

number_of_matches = sum( ...
    strcmp( ...
        summary_rows(:, 5), ...
        requested_status ...
    ) ...
);

end


function value = clean_tsv_field(value)
% Remove tabs and line breaks before writing a TSV field.

value = char( ...
    string(value) ...
);

value = strrep( ...
    value, ...
    sprintf('\t'), ...
    ' ' ...
);

value = strrep( ...
    value, ...
    sprintf('\r'), ...
    ' ' ...
);

value = strrep( ...
    value, ...
    sprintf('\n'), ...
    ' ' ...
);

end


function sorted_directories = natural_sort_subject_directories( ...
    directory_struct ...
)
% Sort participant directories by their numeric identifier.

if isempty(directory_struct)

    sorted_directories = directory_struct;
    return;
end

participant_numbers = nan( ...
    numel(directory_struct), ...
    1 ...
);

for index = 1:numel(directory_struct)

    token = regexp( ...
        directory_struct(index).name, ...
        '\d+', ...
        'match', ...
        'once' ...
    );

    if ~isempty(token)
        participant_numbers(index) = str2double(token);
    end
end

[~, sorting_order] = sort( ...
    participant_numbers ...
);

sorted_directories = directory_struct( ...
    sorting_order ...
);

end


function sorted_directories = sort_directory_struct_by_name( ...
    directory_struct ...
)
% Sort ROI directories alphabetically by name.

if isempty(directory_struct)

    sorted_directories = directory_struct;
    return;
end

names = lower( ...
    string( ...
        {directory_struct.name} ...
    ) ...
);

[~, sorting_order] = sort( ...
    names ...
);

sorted_directories = directory_struct( ...
    sorting_order ...
);

end


function name = strip_nifti_suffix(file_path)
% Return the filename without .nii or .nii.gz.

[~, name, extension] = fileparts( ...
    file_path ...
);

if strcmpi(extension, '.gz')

    [~, name] = fileparts( ...
        name ...
    );
end

end


function output = canonical_path(input_path)
% Return a normalized absolute path for path comparison.

input_file = java.io.File( ...
    input_path ...
);

output = char( ...
    input_file.getCanonicalPath() ...
);

end