function run_rn_vpe_sign_onesample_ttest(varargin)
% =========================================================================
% SPM12 second-level one-sample t-test for RN vPE-sign slope maps
%
% This script performs a second-level one-sample t-test on first-level
% slope maps generated separately for positive- or negative-vPE trials
% during the RN stage.
%
% Two directional contrasts are created:
%
%   1. RN_<sign> > 0
%   2. RN_<sign> < 0
%
% -------------------------------------------------------------------------
% Expected input structure
% -------------------------------------------------------------------------
%
% <first_level_root>/
% └── <ROI_NAME>/
%     ├── Sub02/
%     │   ├── Sub02_<ROI_NAME>_regBeta_GMresid_RN_pos.nii
%     │   └── Sub02_<ROI_NAME>_regBeta_GMresid_RN_neg.nii
%     ├── Sub03/
%     │   └── ...
%     └── ...
%
% Both .nii and .nii.gz input files are supported.
%
% -------------------------------------------------------------------------
% Default output structure
% -------------------------------------------------------------------------
%
% <second_level_root>/
% └── <ROI_NAME>/
%     └── RN_<sign>_onesample/
%         ├── SPM.mat
%         ├── con_0001.nii
%         ├── con_0002.nii
%         ├── spmT_0001.nii
%         ├── spmT_0002.nii
%         ├── included_subjects.txt
%         └── batch_one_sample_t.mat
%
% -------------------------------------------------------------------------
% Example
% -------------------------------------------------------------------------
%
% run_rn_vpe_sign_onesample_ttest( ...
%     'first_level_root', '/path/to/first_level_results', ...
%     'second_level_root', '/path/to/second_level_results', ...
%     'roi_name', 'ROI_NAME', ...
%     'sign_name', 'pos');
%
% Negative-vPE analysis:
%
% run_rn_vpe_sign_onesample_ttest( ...
%     'roi_name', 'ROI_NAME', ...
%     'sign_name', 'neg');
%
% With an explicit mask:
%
% run_rn_vpe_sign_onesample_ttest( ...
%     'roi_name', 'ROI_NAME', ...
%     'sign_name', 'pos', ...
%     'explicit_mask', '/path/to/group_mask.nii');
%
% Dependency
% ----------
% SPM12
% =========================================================================

clc;

%% ========================================================================
% 0. Parse settings
% ========================================================================

script_path = mfilename('fullpath');
script_dir = fileparts(script_path);

default_first_level_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'rn_vpe_sign_regression' ...
);

default_second_level_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'rn_vpe_sign_second_level' ...
);

parser = inputParser;

addParameter( ...
    parser, ...
    'first_level_root', ...
    default_first_level_root, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'second_level_root', ...
    default_second_level_root, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'roi_name', ...
    '', ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'sign_name', ...
    'pos', ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'explicit_mask', ...
    '', ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'minimum_subjects', ...
    3, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 2 ...
);

addParameter( ...
    parser, ...
    'overwrite_existing', ...
    true, ...
    @(x) islogical(x) && isscalar(x) ...
);

addParameter( ...
    parser, ...
    'affine_tolerance', ...
    1e-4, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0 ...
);

parse(parser, varargin{:});

first_level_root = char( ...
    parser.Results.first_level_root ...
);

second_level_root = char( ...
    parser.Results.second_level_root ...
);

roi_name = strtrim( ...
    char(parser.Results.roi_name) ...
);

sign_name = normalize_sign_name( ...
    parser.Results.sign_name ...
);

explicit_mask = char( ...
    parser.Results.explicit_mask ...
);

minimum_subjects = ...
    parser.Results.minimum_subjects;

overwrite_existing = ...
    parser.Results.overwrite_existing;

affine_tolerance = ...
    parser.Results.affine_tolerance;

if isempty(roi_name)
    error( ...
        ['The ROI name is required. Example:\n', ...
         'run_rn_vpe_sign_onesample_ttest(', ...
         '''roi_name'', ''ROI_NAME'', ''sign_name'', ''pos'');'] ...
    );
end

%% ========================================================================
% 1. Validate SPM and input paths
% ========================================================================

if exist('spm', 'file') ~= 2
    error( ...
        ['SPM12 was not found on the MATLAB path. ', ...
         'Install SPM12 and add it to the MATLAB path.'] ...
    );
end

if exist(first_level_root, 'dir') ~= 7
    error( ...
        'First-level root directory does not exist:\n%s', ...
        first_level_root ...
    );
end

roi_directory = fullfile( ...
    first_level_root, ...
    roi_name ...
);

if exist(roi_directory, 'dir') ~= 7
    error( ...
        'ROI directory does not exist:\n%s', ...
        roi_directory ...
    );
end

if ...
        ~isempty(explicit_mask) ...
        && exist(explicit_mask, 'file') ~= 2

    error( ...
        'Explicit mask does not exist:\n%s', ...
        explicit_mask ...
    );
end

if exist(second_level_root, 'dir') ~= 7
    mkdir(second_level_root);
end

output_directory = fullfile( ...
    second_level_root, ...
    roi_name, ...
    sprintf( ...
        'RN_%s_onesample', ...
        sign_name ...
    ) ...
);

input_cache_directory = fullfile( ...
    second_level_root, ...
    '_spm_input_cache', ...
    roi_name, ...
    sprintf( ...
        'RN_%s', ...
        sign_name ...
    ) ...
);

if exist(input_cache_directory, 'dir') ~= 7
    mkdir(input_cache_directory);
end

%% ========================================================================
% 2. Initialize SPM
% ========================================================================

spm('defaults', 'FMRI');
spm_jobman('initcfg');

%% ========================================================================
% 3. Prepare optional explicit mask
% ========================================================================

if isempty(explicit_mask)

    prepared_explicit_mask = '';

else
    mask_cache_directory = fullfile( ...
        second_level_root, ...
        '_spm_input_cache', ...
        'explicit_mask' ...
    );

    prepared_mask_path = prepare_spm_nifti( ...
        explicit_mask, ...
        mask_cache_directory ...
    );

    prepared_explicit_mask = add_volume_index( ...
        prepared_mask_path ...
    );
end

%% ========================================================================
% 4. Detect participant directories
% ========================================================================

subject_directories = detect_subject_directories( ...
    roi_directory ...
);

if isempty(subject_directories)
    error( ...
        'No participant directories matching Sub<number> were found in:\n%s', ...
        roi_directory ...
    );
end

fprintf('\n============================================================\n');
fprintf('RN vPE-sign second-level one-sample t-test\n');
fprintf('============================================================\n');

fprintf( ...
    'First-level root:    %s\n', ...
    first_level_root ...
);

fprintf( ...
    'ROI:                 %s\n', ...
    roi_name ...
);

fprintf( ...
    'vPE-sign group:      %s\n', ...
    sign_name ...
);

fprintf( ...
    'Second-level output: %s\n', ...
    output_directory ...
);

fprintf( ...
    'Minimum subjects:    %d\n', ...
    minimum_subjects ...
);

fprintf( ...
    'Overwrite existing:  %d\n', ...
    overwrite_existing ...
);

if isempty(explicit_mask)
    fprintf('Explicit mask:       none\n');
else
    fprintf( ...
        'Explicit mask:       %s\n', ...
        explicit_mask ...
    );
end

fprintf('============================================================\n');

%% ========================================================================
% 5. Collect participant-level slope maps
% ========================================================================

scans = {};
included_subjects = {};

for subject_index = 1:numel(subject_directories)

    subject_name = ...
        subject_directories(subject_index).name;

    subject_directory = fullfile( ...
        roi_directory, ...
        subject_name ...
    );

    source_image = find_slope_map( ...
        subject_directory, ...
        subject_name, ...
        roi_name, ...
        sign_name ...
    );

    if isempty(source_image)

        expected_filename = sprintf( ...
            '%s_%s_regBeta_GMresid_RN_%s.nii', ...
            subject_name, ...
            roi_name, ...
            sign_name ...
        );

        fprintf( ...
            '[Missing] %s\n', ...
            fullfile( ...
                subject_directory, ...
                expected_filename ...
            ) ...
        );

        continue;
    end

    subject_cache_directory = fullfile( ...
        input_cache_directory, ...
        subject_name ...
    );

    try
        prepared_image = prepare_spm_nifti( ...
            source_image, ...
            subject_cache_directory ...
        );

    catch preparation_error

        fprintf( ...
            '[Skipped] Could not prepare %s: %s\n', ...
            subject_name, ...
            preparation_error.message ...
        );

        continue;
    end

    scans{end + 1, 1} = ...
        add_volume_index(prepared_image); %#ok<AGROW>

    included_subjects{end + 1, 1} = ...
        subject_name; %#ok<AGROW>
end

number_of_subjects = numel(scans);

fprintf( ...
    '\nParticipant maps found: %d\n', ...
    number_of_subjects ...
);

if number_of_subjects < minimum_subjects
    error( ...
        ['Too few participant maps for the one-sample t-test: ', ...
         '%d < %d'], ...
        number_of_subjects, ...
        minimum_subjects ...
    );
end

%% ========================================================================
% 6. Validate input image grids
% ========================================================================

validate_scan_grids( ...
    scans, ...
    prepared_explicit_mask, ...
    affine_tolerance ...
);

%% ========================================================================
% 7. Prepare output directory
% ========================================================================

prepare_output_directory( ...
    output_directory, ...
    overwrite_existing ...
);

%% ========================================================================
% 8. Specify the one-sample t-test
% ========================================================================

matlabbatch = {};

% -------------------------------------------------------------------------
% Group-level factorial design
% -------------------------------------------------------------------------

matlabbatch{1}.spm.stats.factorial_design.dir = {
    output_directory
};

matlabbatch{1}.spm.stats.factorial_design ...
    .des.t1.scans = scans;

% No covariates.
matlabbatch{1}.spm.stats.factorial_design.cov = ...
    struct( ...
        'c', {}, ...
        'cname', {}, ...
        'iCFI', {}, ...
        'iCC', {} ...
    );

matlabbatch{1}.spm.stats.factorial_design.multi_cov = ...
    struct( ...
        'files', {}, ...
        'iCFI', {}, ...
        'iCC', {} ...
    );

% Disable threshold masking.
matlabbatch{1}.spm.stats.factorial_design ...
    .masking.tm.tm_none = 1;

% Enable implicit masking.
matlabbatch{1}.spm.stats.factorial_design ...
    .masking.im = 1;

if isempty(prepared_explicit_mask)

    matlabbatch{1}.spm.stats.factorial_design ...
        .masking.em = {''};

else
    matlabbatch{1}.spm.stats.factorial_design ...
        .masking.em = {
            prepared_explicit_mask
        };
end

% Disable global calculation and scaling.
matlabbatch{1}.spm.stats.factorial_design ...
    .globalc.g_omit = 1;

matlabbatch{1}.spm.stats.factorial_design ...
    .globalm.gmsca.gmsca_no = 1;

matlabbatch{1}.spm.stats.factorial_design ...
    .globalm.glonorm = 1;

%% ========================================================================
% 9. Estimate the group-level model
% ========================================================================

spm_mat_path = fullfile( ...
    output_directory, ...
    'SPM.mat' ...
);

matlabbatch{2}.spm.stats.fmri_est.spmmat = {
    spm_mat_path
};

matlabbatch{2}.spm.stats.fmri_est ...
    .write_residuals = 0;

matlabbatch{2}.spm.stats.fmri_est ...
    .method.Classical = 1;

%% ========================================================================
% 10. Define positive and negative contrasts
% ========================================================================

matlabbatch{3}.spm.stats.con.spmmat = {
    spm_mat_path
};

matlabbatch{3}.spm.stats.con.delete = 1;

matlabbatch{3}.spm.stats.con.consess{1} ...
    .tcon.name = sprintf( ...
        'RN_%s > 0', ...
        sign_name ...
    );

matlabbatch{3}.spm.stats.con.consess{1} ...
    .tcon.weights = 1;

matlabbatch{3}.spm.stats.con.consess{1} ...
    .tcon.sessrep = 'none';

matlabbatch{3}.spm.stats.con.consess{2} ...
    .tcon.name = sprintf( ...
        'RN_%s < 0', ...
        sign_name ...
    );

matlabbatch{3}.spm.stats.con.consess{2} ...
    .tcon.weights = -1;

matlabbatch{3}.spm.stats.con.consess{2} ...
    .tcon.sessrep = 'none';

%% ========================================================================
% 11. Save and run the SPM batch
% ========================================================================

batch_path = fullfile( ...
    output_directory, ...
    'batch_one_sample_t.mat' ...
);

save( ...
    batch_path, ...
    'matlabbatch' ...
);

spm_jobman( ...
    'run', ...
    matlabbatch ...
);

write_subject_manifest( ...
    output_directory, ...
    included_subjects ...
);

fprintf('\n============================================================\n');
fprintf('One-sample t-test completed\n');
fprintf('============================================================\n');

fprintf( ...
    'ROI:                 %s\n', ...
    roi_name ...
);

fprintf( ...
    'vPE-sign group:      %s\n', ...
    sign_name ...
);

fprintf( ...
    'Participants:        %d\n', ...
    number_of_subjects ...
);

fprintf( ...
    'Output directory:    %s\n', ...
    output_directory ...
);

fprintf('============================================================\n');

end


%% ========================================================================
% Local helper functions
% ========================================================================

function sign_name = normalize_sign_name(input_sign)
% Normalize and validate the vPE-sign group name.

sign_name = lower( ...
    strtrim( ...
        char(input_sign) ...
    ) ...
);

if ~ismember( ...
        sign_name, ...
        {'pos', 'neg'} ...
    )

    error( ...
        'sign_name must be either ''pos'' or ''neg''.' ...
    );
end

end


function subject_directories = detect_subject_directories(roi_directory)
% Detect participant directories matching Sub<number>.

all_directories = dir( ...
    fullfile( ...
        roi_directory, ...
        'Sub*' ...
    ) ...
);

all_directories = all_directories( ...
    [all_directories.isdir] ...
);

keep = false( ...
    numel(all_directories), ...
    1 ...
);

for index = 1:numel(all_directories)

    keep(index) = ~isempty( ...
        regexp( ...
            all_directories(index).name, ...
            '^Sub\d+$', ...
            'once' ...
        ) ...
    );
end

subject_directories = all_directories(keep);

subject_directories = natural_sort_subject_directories( ...
    subject_directories ...
);

end


function slope_map = find_slope_map( ...
    subject_directory, ...
    subject_name, ...
    roi_name, ...
    sign_name ...
)
% Locate an uncompressed or compressed first-level slope map.

base_name = sprintf( ...
    '%s_%s_regBeta_GMresid_RN_%s', ...
    subject_name, ...
    roi_name, ...
    sign_name ...
);

candidate_paths = {
    fullfile( ...
        subject_directory, ...
        [base_name, '.nii'] ...
    ), ...
    fullfile( ...
        subject_directory, ...
        [base_name, '.nii.gz'] ...
    ) ...
};

slope_map = '';

for index = 1:numel(candidate_paths)

    if exist(candidate_paths{index}, 'file') == 2

        slope_map = candidate_paths{index};
        return;
    end
end

end


function prepared_path = prepare_spm_nifti( ...
    input_path, ...
    cache_directory ...
)
% Return an uncompressed NIfTI path suitable for SPM.
%
% Uncompressed .nii inputs are used directly. Compressed .nii.gz inputs
% are decompressed into a cache directory.

input_path = char(input_path);

if exist(input_path, 'file') ~= 2
    error( ...
        'Input image does not exist: %s', ...
        input_path ...
    );
end

if endsWith( ...
        lower(input_path), ...
        '.nii' ...
    )

    prepared_path = input_path;
    return;
end

if ~endsWith( ...
        lower(input_path), ...
        '.nii.gz' ...
    )

    error( ...
        'Unsupported image extension: %s', ...
        input_path ...
    );
end

if exist(cache_directory, 'dir') ~= 7
    mkdir(cache_directory);
end

output_filename = [
    strip_nifti_suffix(input_path), ...
    '.nii' ...
];

prepared_path = fullfile( ...
    cache_directory, ...
    output_filename ...
);

source_information = dir( ...
    input_path ...
);

target_information = dir( ...
    prepared_path ...
);

needs_extraction = ...
    isempty(target_information) ...
    || target_information.datenum < source_information.datenum;

if needs_extraction

    if exist(prepared_path, 'file') == 2
        delete(prepared_path);
    end

    extracted_files = gunzip( ...
        input_path, ...
        cache_directory ...
    );

    if isempty(extracted_files)
        error( ...
            'Failed to decompress NIfTI file: %s', ...
            input_path ...
        );
    end
end

if exist(prepared_path, 'file') ~= 2
    error( ...
        'Decompressed image was not created: %s', ...
        prepared_path ...
    );
end

end


function indexed_path = add_volume_index(file_path)
% Add the SPM volume suffix ",1" when it is absent.

file_path = char(file_path);

if isempty( ...
        regexp( ...
            file_path, ...
            ',\d+$', ...
            'once' ...
        ) ...
    )

    indexed_path = [
        file_path, ...
        ',1' ...
    ];

else
    indexed_path = file_path;
end

end


function clean_path = remove_volume_index(indexed_path)
% Remove a trailing SPM volume suffix such as ",1".

clean_path = regexprep( ...
    char(indexed_path), ...
    ',\d+$', ...
    '' ...
);

end


function validate_scan_grids( ...
    scans, ...
    explicit_mask, ...
    affine_tolerance ...
)
% Verify that all participant maps share dimensions and affine matrices.

reference_path = remove_volume_index( ...
    scans{1} ...
);

reference_volume = spm_vol( ...
    reference_path ...
);

reference_dimensions = ...
    reference_volume(1).dim;

reference_affine = ...
    reference_volume(1).mat;

for index = 1:numel(scans)

    current_path = remove_volume_index( ...
        scans{index} ...
    );

    current_volume = spm_vol( ...
        current_path ...
    );

    if ~isequal( ...
            current_volume(1).dim, ...
            reference_dimensions ...
        )

        error( ...
            ['Image dimensions do not match.\n', ...
             'Reference: %s\nCurrent: %s'], ...
            reference_path, ...
            current_path ...
        );
    end

    maximum_affine_difference = max( ...
        abs( ...
            current_volume(1).mat(:) ...
            - reference_affine(:) ...
        ) ...
    );

    if maximum_affine_difference > affine_tolerance

        error( ...
            ['Image affine does not match.\n', ...
             'Reference: %s\nCurrent: %s\n', ...
             'Maximum difference: %.8g'], ...
            reference_path, ...
            current_path, ...
            maximum_affine_difference ...
        );
    end
end

if ~isempty(explicit_mask)

    mask_path = remove_volume_index( ...
        explicit_mask ...
    );

    mask_volume = spm_vol( ...
        mask_path ...
    );

    if ~isequal( ...
            mask_volume(1).dim, ...
            reference_dimensions ...
        )

        error( ...
            ['Explicit-mask dimensions do not match the input maps.\n', ...
             'Mask: %s\nReference: %s'], ...
            mask_path, ...
            reference_path ...
        );
    end

    maximum_mask_affine_difference = max( ...
        abs( ...
            mask_volume(1).mat(:) ...
            - reference_affine(:) ...
        ) ...
    );

    if maximum_mask_affine_difference > affine_tolerance

        error( ...
            ['Explicit-mask affine does not match the input maps.\n', ...
             'Mask: %s\nReference: %s\n', ...
             'Maximum difference: %.8g'], ...
            mask_path, ...
            reference_path, ...
            maximum_mask_affine_difference ...
        );
    end
end

end


function prepare_output_directory( ...
    output_directory, ...
    overwrite_existing ...
)
% Create the output directory and selectively remove an existing SPM model.

if exist(output_directory, 'dir') ~= 7

    mkdir(output_directory);
    return;
end

existing_spm = fullfile( ...
    output_directory, ...
    'SPM.mat' ...
);

if exist(existing_spm, 'file') ~= 2
    return;
end

if ~overwrite_existing

    error( ...
        ['An existing SPM model was found in:\n%s\n', ...
         'Set overwrite_existing=true to replace it.'], ...
        output_directory ...
    );
end

patterns_to_remove = {
    'SPM.mat', ...
    'mask.nii', ...
    'mask.nii.gz', ...
    'ResMS.nii', ...
    'ResMS.nii.gz', ...
    'RPV.nii', ...
    'RPV.nii.gz', ...
    'beta_*.nii', ...
    'beta_*.nii.gz', ...
    'con_*.nii', ...
    'con_*.nii.gz', ...
    'spmT_*.nii', ...
    'spmT_*.nii.gz', ...
    'spmF_*.nii', ...
    'spmF_*.nii.gz', ...
    'ess_*.nii', ...
    'ess_*.nii.gz', ...
    'ResI_*.nii', ...
    'ResI_*.nii.gz', ...
    'batch_one_sample_t.mat', ...
    'included_subjects.txt' ...
};

for pattern_index = 1:numel(patterns_to_remove)

    matching_files = dir( ...
        fullfile( ...
            output_directory, ...
            patterns_to_remove{pattern_index} ...
        ) ...
    );

    for file_index = 1:numel(matching_files)

        file_path = fullfile( ...
            output_directory, ...
            matching_files(file_index).name ...
        );

        if exist(file_path, 'file') == 2
            delete(file_path);
        end
    end
end

end


function write_subject_manifest( ...
    output_directory, ...
    subject_names ...
)
% Save the participant IDs included in the group-level model.

manifest_path = fullfile( ...
    output_directory, ...
    'included_subjects.txt' ...
);

file_id = fopen( ...
    manifest_path, ...
    'w' ...
);

if file_id == -1
    warning( ...
        'Could not create participant manifest: %s', ...
        manifest_path ...
    );
    return;
end

for index = 1:numel(subject_names)

    fprintf( ...
        file_id, ...
        '%s\n', ...
        subject_names{index} ...
    );
end

fclose(file_id);

end


function sorted_directories = natural_sort_subject_directories( ...
    directory_struct ...
)
% Sort participant directories by numeric participant identifier.

if isempty(directory_struct)

    sorted_directories = directory_struct;
    return;
end

participant_numbers = nan( ...
    numel(directory_struct), ...
    1 ...
);

for index = 1:numel(directory_struct)

    numeric_token = regexp( ...
        directory_struct(index).name, ...
        '\d+', ...
        'match', ...
        'once' ...
    );

    if ~isempty(numeric_token)

        participant_numbers(index) = str2double( ...
            numeric_token ...
        );
    end
end

[~, sorting_order] = sort( ...
    participant_numbers ...
);

sorted_directories = directory_struct( ...
    sorting_order ...
);

end


function name = strip_nifti_suffix(file_path)
% Return the filename without .nii or .nii.gz.

[~, name, extension] = fileparts( ...
    file_path ...
);

if strcmpi(extension, '.gz')

    [~, name] = fileparts( ...
        name ...
    );
end

end