function run_lss_outcome(varargin)
% =========================================================================
% Trial-wise outcome-locked LSS analysis
%
% Public-release version:
%   1. No machine-specific absolute paths.
%   2. Input and output paths are supplied using name-value arguments.
%
% -------------------------------------------------------------------------
% Expected directory structure
% -------------------------------------------------------------------------
%
% project/
% ├── run_lss_outcome.m
% ├── data/
% │   ├── func/
% │   │   ├── sub-002_task-gonogo_space-...
% │   │   │   _desc-preproc_merged_sm2mm_bold.nii
% │   │   └── ...
% │   ├── onsets/
% │   │   ├── Sub02/
% │   │   │   └── Onset_outcome_all.mat
% │   │   └── ...
% │   └── confounds/
% │       ├── Sub02/
% │       │   └── confounds.txt
% │       ├── Sub03/
% │       │   └── confounds.txt
% │       └── ...
% └── outputs/
%     └── lss_outcome/
%
% -------------------------------------------------------------------------
% Example
% -------------------------------------------------------------------------
%
% run_lss_outcome( ...
%     'func_dir', '/path/to/func', ...
%     'onset_root', '/path/to/onsets', ...
%     'confounds_root', '/path/to/confounds', ...
%     'output_root', '/path/to/lss_output');
%
% Run selected participants only:
%
% run_lss_outcome( ...
%     'subject_list', {'sub-002', 'sub-032'});
%
% -------------------------------------------------------------------------
% Dependencies
% -------------------------------------------------------------------------
%   SPM12
%   MATLAB Parallel Computing Toolbox
% =========================================================================

clc;

%% ========================================================================
% 0. Parse settings
% ========================================================================

script_path = mfilename('fullpath');
script_dir = fileparts(script_path);

default_data_root = fullfile( ...
    script_dir, ...
    'data' ...
);

default_output_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'lss_outcome' ...
);

parser = inputParser;

addParameter( ...
    parser, ...
    'func_dir', ...
    fullfile(default_data_root, 'func'), ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'onset_root', ...
    fullfile(default_data_root, 'onsets'), ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'confounds_root', ...
    fullfile(default_data_root, 'confounds'), ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'output_root', ...
    default_output_root, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'subject_list', ...
    {}, ...
    @(x) iscell(x) || ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'task_name', ...
    'gonogo', ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'space_name', ...
    'MNI152NLin2009cAsym_res-2', ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'TR', ...
    2.2, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0 ...
);

addParameter( ...
    parser, ...
    'event_duration', ...
    0.5, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0 ...
);

addParameter( ...
    parser, ...
    'n_workers', ...
    8, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 ...
);

addParameter( ...
    parser, ...
    'delete_trial_dir_after_success', ...
    true, ...
    @(x) islogical(x) && isscalar(x) ...
);

parse(parser, varargin{:});

root_func_dir = char(parser.Results.func_dir);
onset_root = char(parser.Results.onset_root);
confounds_root = char(parser.Results.confounds_root);
root_out_path = char(parser.Results.output_root);

task_name = char(parser.Results.task_name);
space_name = char(parser.Results.space_name);

TR = parser.Results.TR;
event_duration = parser.Results.event_duration;
n_workers = parser.Results.n_workers;

delete_trial_dir_after_success = ...
    parser.Results.delete_trial_dir_after_success;

subject_list = parser.Results.subject_list;

if ischar(subject_list) || isstring(subject_list)
    subject_list = cellstr(subject_list);
end

% Analysis labels and onset settings.
lss_label = 'outcome';
onset_mat_name = 'Onset_outcome_all.mat';
onset_var_name = 'onset_outcome_all';

% Fixed confound filename for every participant.
confounds_filename = 'confounds.txt';

% SPM timing and filtering settings.
FMRI_T = 16;
FMRI_T0 = 8;
HPF = 128;

%% ========================================================================
% 1. Validate software and input directories
% ========================================================================

if exist('spm', 'file') ~= 2
    error( ...
        ['SPM12 was not found on the MATLAB path. ', ...
         'Install SPM12 and add it to the MATLAB path.'] ...
    );
end

if isempty(ver('parallel'))
    error( ...
        ['MATLAB Parallel Computing Toolbox was not found. ', ...
         'This script uses parfor for trial-wise analyses.'] ...
    );
end

required_directories = {
    root_func_dir, ...
    onset_root, ...
    confounds_root ...
};

required_directory_names = {
    'Functional image directory', ...
    'Onset root directory', ...
    'Confounds root directory' ...
};

for directory_index = 1:numel(required_directories)

    current_directory = ...
        required_directories{directory_index};

    if exist(current_directory, 'dir') ~= 7
        error( ...
            '%s does not exist:\n%s', ...
            required_directory_names{directory_index}, ...
            current_directory ...
        );
    end
end

if exist(root_out_path, 'dir') ~= 7
    mkdir(root_out_path);
end

fprintf('\n============================================================\n');
fprintf('Outcome-locked LSS analysis with confounds\n');
fprintf('============================================================\n');

fprintf('Functional directory: %s\n', root_func_dir);
fprintf('Onset root:           %s\n', onset_root);
fprintf('Confounds root:       %s\n', confounds_root);
fprintf('Output root:          %s\n', root_out_path);
fprintf('Confounds filename:   %s\n', confounds_filename);
fprintf('TR:                   %.3f seconds\n', TR);
fprintf('Event duration:       %.3f seconds\n', event_duration);
fprintf('Parallel workers:     %d\n', n_workers);

fprintf('============================================================\n');

%% ========================================================================
% 2. Detect participants from functional images
% ========================================================================

if isempty(subject_list)

    subject_list = detect_subjects_from_functional_files( ...
        root_func_dir, ...
        task_name, ...
        space_name ...
    );

    if isempty(subject_list)
        error( ...
            ['No functional images matching the expected naming rule ', ...
             'were found in:\n%s'], ...
            root_func_dir ...
        );
    end

else
    subject_list = normalize_subject_list( ...
        subject_list ...
    );
end

fprintf( ...
    '\nDetected %d participants:\n', ...
    numel(subject_list) ...
);

fprintf( ...
    '  %s\n', ...
    strjoin(subject_list, ', ') ...
);

%% ========================================================================
% 3. Initialize SPM and parallel pool
% ========================================================================

spm('Defaults', 'fMRI');
spm_jobman('initcfg');

parallel_pool = gcp('nocreate');

if isempty(parallel_pool)

    parpool( ...
        'local', ...
        n_workers ...
    );

elseif parallel_pool.NumWorkers ~= n_workers

    fprintf( ...
        ['An existing parallel pool with %d workers will be used ', ...
         'instead of the requested %d workers.\n'], ...
        parallel_pool.NumWorkers, ...
        n_workers ...
    );
end

%% ========================================================================
% 4. Main participant loop
% ========================================================================

for subject_index = 1:numel(subject_list)

    subject_bids = subject_list{subject_index};

    subject_number_string = regexp( ...
        subject_bids, ...
        '\d+', ...
        'match', ...
        'once' ...
    );

    fprintf('\n============================================================\n');

    fprintf( ...
        'Processing participant %d/%d: %s\n', ...
        subject_index, ...
        numel(subject_list), ...
        subject_bids ...
    );

    fprintf('============================================================\n');

    %% --------------------------------------------------------------------
    % 4.1 Locate functional image
    % ---------------------------------------------------------------------

    functional_file = find_functional_file( ...
        root_func_dir, ...
        subject_bids, ...
        task_name, ...
        space_name ...
    );

    if isempty(functional_file)

        fprintf( ...
            'Functional image not found for %s. Participant skipped.\n', ...
            subject_bids ...
        );

        continue;
    end

    %% --------------------------------------------------------------------
    % 4.2 Locate onset folder and onset file
    % ---------------------------------------------------------------------

    onset_directory_name = pick_subject_directory( ...
        onset_root, ...
        subject_number_string ...
    );

    if isempty(onset_directory_name)

        fprintf( ...
            'Onset directory not found for %s. Participant skipped.\n', ...
            subject_bids ...
        );

        continue;
    end

    onset_mat = fullfile( ...
        onset_root, ...
        onset_directory_name, ...
        onset_mat_name ...
    );

    if exist(onset_mat, 'file') ~= 2

        fprintf( ...
            'Outcome-onset file not found: %s\n', ...
            onset_mat ...
        );

        continue;
    end

    %% --------------------------------------------------------------------
    % 4.3 Locate fixed confounds.txt
    % ---------------------------------------------------------------------

    confounds_directory_name = pick_subject_directory( ...
        confounds_root, ...
        subject_number_string ...
    );

    if isempty(confounds_directory_name)

        fprintf( ...
            'Confounds directory not found for %s. Participant skipped.\n', ...
            subject_bids ...
        );

        continue;
    end

    confounds_file_raw = fullfile( ...
        confounds_root, ...
        confounds_directory_name, ...
        confounds_filename ...
    );

    if exist(confounds_file_raw, 'file') ~= 2

        fprintf( ...
            'Confounds file not found: %s\n', ...
            confounds_file_raw ...
        );

        continue;
    end

    %% --------------------------------------------------------------------
    % 4.4 Prepare participant output directory
    % ---------------------------------------------------------------------

    output_subject_directory = fullfile( ...
        root_out_path, ...
        sprintf( ...
            '%s_LSS_%s', ...
            onset_directory_name, ...
            lss_label ...
        ) ...
    );

    if exist(output_subject_directory, 'dir') ~= 7
        mkdir(output_subject_directory);
    end

    specification_log = fullfile( ...
        output_subject_directory, ...
        'spec_log.txt' ...
    );

    participant_error_log = fullfile( ...
        output_subject_directory, ...
        'subject_error.txt' ...
    );

    write_log( ...
        specification_log, ...
        sprintf( ...
            '\n[%s] Starting participant %s', ...
            datestr(now), ...
            subject_bids ...
        ) ...
    );

    write_log( ...
        specification_log, ...
        sprintf( ...
            'Functional image: %s', ...
            functional_file ...
        ) ...
    );

    write_log( ...
        specification_log, ...
        sprintf( ...
            'Outcome onsets: %s', ...
            onset_mat ...
        ) ...
    );

    write_log( ...
        specification_log, ...
        sprintf( ...
            'Confounds: %s', ...
            confounds_file_raw ...
        ) ...
    );

    try
        %% ----------------------------------------------------------------
        % 4.5 Load functional volumes
        % -----------------------------------------------------------------

        functional_volumes = spm_vol( ...
            functional_file ...
        );

        number_of_scans = numel( ...
            functional_volumes ...
        );

        functional_scans = arrayfun( ...
            @(volume_index) sprintf( ...
                '%s,%d', ...
                functional_file, ...
                volume_index ...
            ), ...
            (1:number_of_scans)', ...
            'UniformOutput', ...
            false ...
        );

        fprintf( ...
            'Number of functional volumes: %d\n', ...
            number_of_scans ...
        );

        write_log( ...
            specification_log, ...
            sprintf( ...
                'Number of functional volumes: %d', ...
                number_of_scans ...
            ) ...
        );

        %% ----------------------------------------------------------------
        % 4.6 Load and validate outcome onsets
        % -----------------------------------------------------------------

        onset_structure = load( ...
            onset_mat, ...
            onset_var_name ...
        );

        assert( ...
            isfield( ...
                onset_structure, ...
                onset_var_name ...
            ), ...
            'Outcome-onset file does not contain variable: %s', ...
            onset_var_name ...
        );

        raw_onsets = double( ...
            onset_structure.(onset_var_name)(:) ...
        );

        % Sampling time of the final acquired volume.
        final_sampling_time = ...
            (number_of_scans - 1) * TR;

        valid_onsets = ...
            isfinite(raw_onsets) ...
            & raw_onsets >= 0 ...
            & raw_onsets <= final_sampling_time;

        if ~all(valid_onsets)

            invalid_indices = find( ...
                ~valid_onsets ...
            );

            write_log( ...
                specification_log, ...
                sprintf( ...
                    'Dropped invalid outcome-onset indices: %s', ...
                    mat2str(invalid_indices') ...
                ) ...
            );
        end

        trial_onsets = raw_onsets( ...
            valid_onsets ...
        );

        number_of_trials = numel( ...
            trial_onsets ...
        );

        fprintf( ...
            'Valid outcome trials: %d / raw outcome onsets: %d\n', ...
            number_of_trials, ...
            numel(raw_onsets) ...
        );

        write_log( ...
            specification_log, ...
            sprintf( ...
                'Valid outcome trials: %d / raw outcome onsets: %d', ...
                number_of_trials, ...
                numel(raw_onsets) ...
            ) ...
        );

        assert( ...
            number_of_trials >= 1, ...
            'No valid outcome trials remained after onset validation.' ...
        );

        %% ----------------------------------------------------------------
        % 4.7 Load and validate confounds
        % -----------------------------------------------------------------

        confounds_clean_file = fullfile( ...
            output_subject_directory, ...
            'confounds.txt' ...
        );

        confounds_matrix = readmatrix( ...
            confounds_file_raw ...
        );

        assert( ...
            isnumeric(confounds_matrix), ...
            'Confounds file does not contain a numeric matrix: %s', ...
            confounds_file_raw ...
        );

        assert( ...
            ~isempty(confounds_matrix), ...
            'Confounds file is empty: %s', ...
            confounds_file_raw ...
        );

        % Automatically transpose when the number of columns equals the
        % number of fMRI volumes but the number of rows does not.
        %
        % This supports accidentally transposed confound matrices without
        % assuming a fixed number of confound columns.
        if ...
                size(confounds_matrix, 1) ~= number_of_scans ...
                && size(confounds_matrix, 2) == number_of_scans

            original_rows = size( ...
                confounds_matrix, ...
                1 ...
            );

            original_columns = size( ...
                confounds_matrix, ...
                2 ...
            );

            confounds_matrix = ...
                confounds_matrix';

            write_log( ...
                specification_log, ...
                sprintf( ...
                    ['Confounds matrix was transposed automatically ', ...
                     'from %d x %d to %d x %d.'], ...
                    original_rows, ...
                    original_columns, ...
                    size(confounds_matrix, 1), ...
                    size(confounds_matrix, 2) ...
                ) ...
            );
        end

        assert( ...
            size(confounds_matrix, 1) == number_of_scans, ...
            ['Confounds row count does not match functional volumes: ', ...
             'confounds=%d rows, functional=%d volumes. File: %s'], ...
            size(confounds_matrix, 1), ...
            number_of_scans, ...
            confounds_file_raw ...
        );

        number_of_confounds = size( ...
            confounds_matrix, ...
            2 ...
        );

        assert( ...
            number_of_confounds >= 1, ...
            'Confounds file contains no regressor columns: %s', ...
            confounds_file_raw ...
        );

        fprintf( ...
            'Confounds matrix: %d rows x %d columns\n', ...
            size(confounds_matrix, 1), ...
            number_of_confounds ...
        );

        write_log( ...
            specification_log, ...
            sprintf( ...
                'Confounds matrix: %d rows x %d columns', ...
                size(confounds_matrix, 1), ...
                number_of_confounds ...
            ) ...
        );

        if any(~isfinite(confounds_matrix(:)))

            number_nonfinite_confounds = nnz( ...
                ~isfinite(confounds_matrix) ...
            );

            write_log( ...
                specification_log, ...
                sprintf( ...
                    ['WARNING: confounds contained %d non-finite ', ...
                     'values; these values were replaced with zero.'], ...
                    number_nonfinite_confounds ...
                ) ...
            );

            confounds_matrix( ...
                ~isfinite(confounds_matrix) ...
            ) = 0;
        end

        writematrix( ...
            confounds_matrix, ...
            confounds_clean_file, ...
            'Delimiter', ...
            'tab' ...
        );

        %% ----------------------------------------------------------------
        % 4.8 Determine completed and pending trials
        % -----------------------------------------------------------------

        completed_trials = false( ...
            number_of_trials, ...
            1 ...
        );

        for trial_index = 1:number_of_trials

            beta_output = fullfile( ...
                output_subject_directory, ...
                sprintf( ...
                    'beta_%s_%03d.nii', ...
                    lss_label, ...
                    trial_index ...
                ) ...
            );

            completed_trials(trial_index) = ...
                is_valid_nifti(beta_output);
        end

        completed_trial_indices = find( ...
            completed_trials ...
        );

        pending_trial_indices = find( ...
            ~completed_trials ...
        );

        fprintf( ...
            'Already completed outcome trials: %d\n', ...
            numel(completed_trial_indices) ...
        );

        fprintf( ...
            'Pending outcome trials: %d\n', ...
            numel(pending_trial_indices) ...
        );

        write_log( ...
            specification_log, ...
            sprintf( ...
                'Already completed outcome trials: %d', ...
                numel(completed_trial_indices) ...
            ) ...
        );

        write_log( ...
            specification_log, ...
            sprintf( ...
                'Pending outcome trials: %d', ...
                numel(pending_trial_indices) ...
            ) ...
        );

        if isempty(pending_trial_indices)

            fprintf( ...
                '%s already completed. Participant skipped.\n', ...
                subject_bids ...
            );

            write_log( ...
                specification_log, ...
                sprintf( ...
                    '[%s] Participant already completed.', ...
                    datestr(now) ...
                ) ...
            );

            continue;
        end

        %% ----------------------------------------------------------------
        % 4.9 Trial-wise LSS GLMs
        % -----------------------------------------------------------------

        parfor pending_index = 1:numel(pending_trial_indices)

            trial_index = pending_trial_indices( ...
                pending_index ...
            );

            spm('Defaults', 'fMRI');
            spm_jobman('initcfg');

            trial_directory = fullfile( ...
                output_subject_directory, ...
                sprintf( ...
                    'LSS_trial_%03d', ...
                    trial_index ...
                ) ...
            );

            beta_output = fullfile( ...
                output_subject_directory, ...
                sprintf( ...
                    'beta_%s_%03d.nii', ...
                    lss_label, ...
                    trial_index ...
                ) ...
            );

            temporary_beta_output = fullfile( ...
                output_subject_directory, ...
                sprintf( ...
                    'beta_%s_%03d.tmp.nii', ...
                    lss_label, ...
                    trial_index ...
                ) ...
            );

            % Resume safeguard.
            if is_valid_nifti(beta_output)
                continue;
            end

            % Remove an incomplete trial directory left by an interrupted run.
            if exist(trial_directory, 'dir') == 7

                try
                    rmdir( ...
                        trial_directory, ...
                        's' ...
                    );
                catch
                end
            end

            if exist(trial_directory, 'dir') ~= 7
                mkdir(trial_directory);
            end

            try
                matlabbatch = {};

                % ---------------------------------------------------------
                % Model specification
                % ---------------------------------------------------------

                matlabbatch{1}.spm.stats.fmri_spec.dir = {
                    trial_directory
                };

                matlabbatch{1}.spm.stats.fmri_spec.timing.units = ...
                    'secs';

                matlabbatch{1}.spm.stats.fmri_spec.timing.RT = ...
                    TR;

                matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t = ...
                    FMRI_T;

                matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t0 = ...
                    FMRI_T0;

                matlabbatch{1}.spm.stats.fmri_spec.sess.scans = ...
                    functional_scans;

                % Current target outcome trial.
                matlabbatch{1}.spm.stats.fmri_spec.sess ...
                    .cond(1).name = sprintf( ...
                        '%s_%03d', ...
                        lss_label, ...
                        trial_index ...
                    );

                matlabbatch{1}.spm.stats.fmri_spec.sess ...
                    .cond(1).onset = trial_onsets( ...
                        trial_index ...
                    );

                matlabbatch{1}.spm.stats.fmri_spec.sess ...
                    .cond(1).duration = event_duration;

                matlabbatch{1}.spm.stats.fmri_spec.sess ...
                    .cond(1).tmod = 0;

                matlabbatch{1}.spm.stats.fmri_spec.sess ...
                    .cond(1).pmod = struct( ...
                        'name', {}, ...
                        'param', {}, ...
                        'poly', {} ...
                    );

                matlabbatch{1}.spm.stats.fmri_spec.sess ...
                    .cond(1).orth = 1;

                % All other outcome trials.
                if number_of_trials > 1

                    other_trial_indices = setdiff( ...
                        1:number_of_trials, ...
                        trial_index ...
                    );

                    matlabbatch{1}.spm.stats.fmri_spec.sess ...
                        .cond(2).name = 'other_outcome_trials';

                    matlabbatch{1}.spm.stats.fmri_spec.sess ...
                        .cond(2).onset = trial_onsets( ...
                            other_trial_indices ...
                        );

                    matlabbatch{1}.spm.stats.fmri_spec.sess ...
                        .cond(2).duration = repmat( ...
                            event_duration, ...
                            numel(other_trial_indices), ...
                            1 ...
                        );

                    matlabbatch{1}.spm.stats.fmri_spec.sess ...
                        .cond(2).tmod = 0;

                    matlabbatch{1}.spm.stats.fmri_spec.sess ...
                        .cond(2).pmod = struct( ...
                            'name', {}, ...
                            'param', {}, ...
                            'poly', {} ...
                        );

                    matlabbatch{1}.spm.stats.fmri_spec.sess ...
                        .cond(2).orth = 1;
                end

                % Confound regressors.
                matlabbatch{1}.spm.stats.fmri_spec.sess.multi = ...
                    {''};

                matlabbatch{1}.spm.stats.fmri_spec.sess.regress = ...
                    struct( ...
                        'name', {}, ...
                        'val', {} ...
                    );

                matlabbatch{1}.spm.stats.fmri_spec.sess.multi_reg = {
                    confounds_clean_file
                };

                matlabbatch{1}.spm.stats.fmri_spec.sess.hpf = ...
                    HPF;

                % HRF basis.
                matlabbatch{1}.spm.stats.fmri_spec.fact = ...
                    struct( ...
                        'name', {}, ...
                        'levels', {} ...
                    );

                matlabbatch{1}.spm.stats.fmri_spec ...
                    .bases.hrf.derivs = [0, 0];

                % Other SPM settings.
                matlabbatch{1}.spm.stats.fmri_spec.volt = 1;

                matlabbatch{1}.spm.stats.fmri_spec.global = ...
                    'None';

                matlabbatch{1}.spm.stats.fmri_spec.mthresh = ...
                    0.8;

                matlabbatch{1}.spm.stats.fmri_spec.mask = ...
                    {''};

                matlabbatch{1}.spm.stats.fmri_spec.cvi = ...
                    'AR(1)';

                % ---------------------------------------------------------
                % Model estimation
                % ---------------------------------------------------------

                matlabbatch{2}.spm.stats.fmri_est.spmmat = {
                    fullfile( ...
                        trial_directory, ...
                        'SPM.mat' ...
                    )
                };

                matlabbatch{2}.spm.stats.fmri_est ...
                    .write_residuals = 0;

                matlabbatch{2}.spm.stats.fmri_est ...
                    .method.Classical = 1;

                spm_jobman( ...
                    'run', ...
                    matlabbatch ...
                );

                % ---------------------------------------------------------
                % Collect target-trial beta image
                % ---------------------------------------------------------

                estimated_beta = fullfile( ...
                    trial_directory, ...
                    'beta_0001.nii' ...
                );

                if exist(estimated_beta, 'file') == 2

                    if exist(temporary_beta_output, 'file') == 2
                        delete(temporary_beta_output);
                    end

                    copyfile( ...
                        estimated_beta, ...
                        temporary_beta_output ...
                    );

                    % Write a temporary output first and move it to the final
                    % filename only after the copy has completed.
                    movefile( ...
                        temporary_beta_output, ...
                        beta_output, ...
                        'f' ...
                    );

                    if delete_trial_dir_after_success

                        try
                            rmdir( ...
                                trial_directory, ...
                                's' ...
                            );
                        catch
                        end
                    end

                else
                    write_trial_error( ...
                        trial_directory, ...
                        trial_index, ...
                        'beta_0001.nii was not generated.', ...
                        [] ...
                    );
                end

            catch trial_error

                write_trial_error( ...
                    trial_directory, ...
                    trial_index, ...
                    trial_error.message, ...
                    trial_error.stack ...
                );

                if exist(temporary_beta_output, 'file') == 2

                    try
                        delete(temporary_beta_output);
                    catch
                    end
                end
            end
        end

        %% ----------------------------------------------------------------
        % 4.10 Check participant completion
        % -----------------------------------------------------------------

        completed_after_run = false( ...
            number_of_trials, ...
            1 ...
        );

        for trial_index = 1:number_of_trials

            beta_output = fullfile( ...
                output_subject_directory, ...
                sprintf( ...
                    'beta_%s_%03d.nii', ...
                    lss_label, ...
                    trial_index ...
                ) ...
            );

            completed_after_run(trial_index) = ...
                is_valid_nifti(beta_output);
        end

        number_completed_after_run = nnz( ...
            completed_after_run ...
        );

        number_missing_after_run = ...
            number_of_trials - number_completed_after_run;

        fprintf( ...
            '\n%s completion check: %d / %d outcome trials completed.\n', ...
            subject_bids, ...
            number_completed_after_run, ...
            number_of_trials ...
        );

        write_log( ...
            specification_log, ...
            sprintf( ...
                '[%s] Final completed outcome trials: %d / %d', ...
                datestr(now), ...
                number_completed_after_run, ...
                number_of_trials ...
            ) ...
        );

        if number_missing_after_run > 0

            missing_trial_indices = find( ...
                ~completed_after_run ...
            );

            write_log( ...
                specification_log, ...
                sprintf( ...
                    'Missing outcome trials after run: %s', ...
                    mat2str(missing_trial_indices') ...
                ) ...
            );

            fprintf( ...
                'Missing outcome trials: %s\n', ...
                mat2str(missing_trial_indices') ...
            );

        else
            fprintf( ...
                '%s outcome LSS completed successfully.\n', ...
                subject_bids ...
            );
        end

    catch participant_error

        file_id = fopen( ...
            participant_error_log, ...
            'a' ...
        );

        if file_id ~= -1

            fprintf( ...
                file_id, ...
                '\n[%s] Participant-level failure: %s\n', ...
                datestr(now), ...
                subject_bids ...
            );

            fprintf( ...
                file_id, ...
                '%s\n', ...
                participant_error.message ...
            );

            if ~isempty(participant_error.stack)

                for stack_index = 1:numel(participant_error.stack)

                    fprintf( ...
                        file_id, ...
                        '  at %s:%d\n', ...
                        participant_error.stack(stack_index).name, ...
                        participant_error.stack(stack_index).line ...
                    );
                end
            end

            fclose(file_id);
        end

        fprintf( ...
            ['Participant %s failed at the participant level. ', ...
             'See: %s\n'], ...
            subject_bids, ...
            participant_error_log ...
        );
    end
end

fprintf( ...
    ['\nAll available participants were completed or skipped ', ...
     'by the resume mechanism.\n'] ...
);

end


%% ========================================================================
% Local helper functions
% ========================================================================

function subject_list = detect_subjects_from_functional_files( ...
    functional_root, ...
    task_name, ...
    space_name ...
)
% Detect participant labels from functional filenames.

patterns = {
    sprintf( ...
        'sub-*_task-%s_space-%s_desc-preproc_merged_sm2mm_bold.nii', ...
        task_name, ...
        space_name ...
    ), ...
    sprintf( ...
        'sub-*_task-%s_space-%s_desc-preproc_merged_sm2mm_bold.nii.gz', ...
        task_name, ...
        space_name ...
    ) ...
};

subject_list = {};

for pattern_index = 1:numel(patterns)

    files = dir( ...
        fullfile( ...
            functional_root, ...
            patterns{pattern_index} ...
        ) ...
    );

    for file_index = 1:numel(files)

        subject_token = regexp( ...
            files(file_index).name, ...
            '^(sub-\d+)_task-', ...
            'tokens', ...
            'once' ...
        );

        if ~isempty(subject_token)

            subject_list{end + 1, 1} = ...
                subject_token{1}; %#ok<AGROW>
        end
    end
end

subject_list = unique( ...
    subject_list, ...
    'stable' ...
);

subject_list = natural_sort_subjects( ...
    subject_list ...
);

end


function subject_list = normalize_subject_list(subject_list)
% Normalize participant identifiers to sub-XXX form.

for index = 1:numel(subject_list)

    current_subject = char( ...
        subject_list{index} ...
    );

    digits = regexp( ...
        current_subject, ...
        '\d+', ...
        'match', ...
        'once' ...
    );

    if isempty(digits)

        error( ...
            'Could not parse participant number from: %s', ...
            current_subject ...
        );
    end

    subject_list{index} = sprintf( ...
        'sub-%03d', ...
        str2double(digits) ...
    );
end

subject_list = unique( ...
    subject_list, ...
    'stable' ...
);

subject_list = natural_sort_subjects( ...
    subject_list ...
);

end


function sorted_subjects = natural_sort_subjects(subject_list)
% Sort participant labels in numerical order.

subject_numbers = zeros( ...
    numel(subject_list), ...
    1 ...
);

for index = 1:numel(subject_list)

    digits = regexp( ...
        subject_list{index}, ...
        '\d+', ...
        'match', ...
        'once' ...
    );

    subject_numbers(index) = str2double( ...
        digits ...
    );
end

[~, sorting_order] = sort( ...
    subject_numbers ...
);

sorted_subjects = subject_list( ...
    sorting_order ...
);

end


function functional_file = find_functional_file( ...
    functional_root, ...
    subject_bids, ...
    task_name, ...
    space_name ...
)
% Find a .nii or .nii.gz functional image.

base_name = sprintf( ...
    '%s_task-%s_space-%s_desc-preproc_merged_sm2mm_bold', ...
    subject_bids, ...
    task_name, ...
    space_name ...
);

candidates = {
    fullfile( ...
        functional_root, ...
        [base_name, '.nii'] ...
    ), ...
    fullfile( ...
        functional_root, ...
        [base_name, '.nii.gz'] ...
    ) ...
};

functional_file = '';

for candidate_index = 1:numel(candidates)

    if exist(candidates{candidate_index}, 'file') == 2

        functional_file = candidates{candidate_index};
        return;
    end
end

end


function subject_folder = pick_subject_directory( ...
    root_directory, ...
    number_string ...
)
% Locate a participant directory using common anonymous naming variants:
%
%   Sub02
%   Sub002
%   Sub2

participant_number = str2double( ...
    number_string ...
);

candidates = {
    fullfile( ...
        root_directory, ...
        sprintf('Sub%02d', participant_number) ...
    ), ...
    fullfile( ...
        root_directory, ...
        sprintf('Sub%03d', participant_number) ...
    ), ...
    fullfile( ...
        root_directory, ...
        sprintf('Sub%d', participant_number) ...
    ), ...
    fullfile( ...
        root_directory, ...
        ['Sub', number_string] ...
    ) ...
};

subject_folder = '';

for candidate_index = 1:numel(candidates)

    if exist(candidates{candidate_index}, 'dir') == 7

        [~, subject_folder] = fileparts( ...
            candidates{candidate_index} ...
        );

        return;
    end
end

end


function valid = is_valid_nifti(nifti_path)
% Return true only when a NIfTI exists and can be read by SPM.

valid = false;

if exist(nifti_path, 'file') ~= 2
    return;
end

try
    volume = spm_vol(nifti_path);

    valid = ...
        ~isempty(volume) ...
        && isfield(volume, 'dim') ...
        && numel(volume(1).dim) == 3;

catch
    valid = false;
end

end


function write_log(log_file, message)
% Append one line to a text log.

file_id = fopen( ...
    log_file, ...
    'a' ...
);

if file_id == -1

    warning( ...
        'Cannot open log file: %s', ...
        log_file ...
    );

    return;
end

fprintf( ...
    file_id, ...
    '%s\n', ...
    message ...
);

fclose(file_id);

end


function write_trial_error( ...
    trial_directory, ...
    trial_index, ...
    error_message, ...
    error_stack ...
)
% Save a trial-level error report.

if exist(trial_directory, 'dir') ~= 7
    mkdir(trial_directory);
end

error_file = fullfile( ...
    trial_directory, ...
    'error.txt' ...
);

file_id = fopen( ...
    error_file, ...
    'w' ...
);

if file_id == -1
    return;
end

fprintf( ...
    file_id, ...
    'Trial %d failed.\n\n', ...
    trial_index ...
);

fprintf( ...
    file_id, ...
    'Error message:\n%s\n\n', ...
    error_message ...
);

if ~isempty(error_stack)

    fprintf( ...
        file_id, ...
        'Stack:\n' ...
    );

    for stack_index = 1:numel(error_stack)

        fprintf( ...
            file_id, ...
            '  at %s:%d\n', ...
            error_stack(stack_index).name, ...
            error_stack(stack_index).line ...
        );
    end
end

fclose(file_id);

end