function run_pattern_change_rn_vs_le_group_stats(varargin)
% =========================================================================
% SPM12 group-level comparison of RN and LE pattern-change maps
%
% Analyses:
%   1. Second-level paired-samples t-test:
%          RN > LE
%          RN < LE
%
%   2. Optional difference-image analysis:
%          Difference image = RN - LE
%          One-sample t-test across participants
%
% -------------------------------------------------------------------------
% Public-release version
% -------------------------------------------------------------------------
% This script contains no user-specific absolute paths, drive letters,
% user names, or machine-specific directory structures.
%
% Paths are supplied through name-value arguments. When omitted, paths are
% resolved relative to the location of this MATLAB file.
%
% -------------------------------------------------------------------------
% Expected input structure
% -------------------------------------------------------------------------
%
% data/
% └── pattern_change_stage_means/
%     ├── Sub02/
%     │   ├── RN/
%     │   │   └── pattern_change_mean_RN.nii
%     │   └── LE/
%     │       └── pattern_change_mean_LE.nii
%     ├── Sub03/
%     │   └── ...
%     └── ...
%
% The following alternative naming scheme is also supported:
%
% data/
% └── pattern_change_stage_means/
%     ├── Sub02/
%     │   ├── RN_mean.nii
%     │   └── LE_mean.nii
%     └── ...
%
% Both .nii and .nii.gz files are supported.
%
% -------------------------------------------------------------------------
% Default outputs
% -------------------------------------------------------------------------
%
% outputs/
% └── pattern_change_group_stats/
%     ├── RN_vs_LE_paired_t/
%     └── RN_minus_LE_one_sample/
%
% -------------------------------------------------------------------------
% Example
% -------------------------------------------------------------------------
%
% run_pattern_change_rn_vs_le_group_stats( ...
%     'mean_root', '/path/to/pattern_change_stage_means', ...
%     'paired_stats_dir', '/path/to/RN_vs_LE_paired_t', ...
%     'difference_stats_dir', '/path/to/RN_minus_LE_one_sample', ...
%     'group_mask', '/path/to/group_GM_mask.nii.gz', ...
%     'run_difference_analysis', true);
%
% To run only the paired t-test:
%
% run_pattern_change_rn_vs_le_group_stats( ...
%     'run_difference_analysis', false);
%
% Dependency:
%   SPM12
% =========================================================================

clc;

%% ========================================================================
% 0. Parse settings
% ========================================================================

script_path = mfilename('fullpath');
script_dir = fileparts(script_path);

default_mean_root = fullfile( ...
    script_dir, ...
    'data', ...
    'pattern_change_stage_means' ...
);

default_group_stats_root = fullfile( ...
    script_dir, ...
    'outputs', ...
    'pattern_change_group_stats' ...
);

default_paired_stats_dir = fullfile( ...
    default_group_stats_root, ...
    'RN_vs_LE_paired_t' ...
);

default_difference_stats_dir = fullfile( ...
    default_group_stats_root, ...
    'RN_minus_LE_one_sample' ...
);

parser = inputParser;

addParameter( ...
    parser, ...
    'mean_root', ...
    default_mean_root, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'paired_stats_dir', ...
    default_paired_stats_dir, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'difference_stats_dir', ...
    default_difference_stats_dir, ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'group_mask', ...
    '', ...
    @(x) ischar(x) || isstring(x) ...
);

addParameter( ...
    parser, ...
    'run_difference_analysis', ...
    true, ...
    @(x) islogical(x) && isscalar(x) ...
);

addParameter( ...
    parser, ...
    'overwrite_existing_stats', ...
    true, ...
    @(x) islogical(x) && isscalar(x) ...
);

parse(parser, varargin{:});

mean_root = char(parser.Results.mean_root);
paired_stats_dir = char(parser.Results.paired_stats_dir);
difference_stats_dir = char(parser.Results.difference_stats_dir);
group_mask = char(parser.Results.group_mask);

run_difference_analysis = ...
    parser.Results.run_difference_analysis;

overwrite_existing_stats = ...
    parser.Results.overwrite_existing_stats;

%% ========================================================================
% 1. Validate SPM and paths
% ========================================================================

if exist('spm', 'file') ~= 2
    error( ...
        ['SPM12 was not found on the MATLAB path. ', ...
         'Install SPM12 and add it to the MATLAB path.'] ...
    );
end

if exist(mean_root, 'dir') ~= 7
    error( ...
        'Mean-map root directory does not exist:\n%s', ...
        mean_root ...
    );
end

if ~isempty(group_mask) && exist(group_mask, 'file') ~= 2
    error( ...
        'Group mask does not exist:\n%s', ...
        group_mask ...
    );
end

prepare_output_directory( ...
    paired_stats_dir, ...
    overwrite_existing_stats ...
);

if run_difference_analysis
    prepare_output_directory( ...
        difference_stats_dir, ...
        overwrite_existing_stats ...
    );
end

fprintf('\n============================================================\n');
fprintf('RN versus LE group-level pattern-change analysis\n');
fprintf('============================================================\n');

fprintf('Mean-map root:             %s\n', mean_root);
fprintf('Paired-test output:        %s\n', paired_stats_dir);
fprintf('Difference-test output:    %s\n', difference_stats_dir);
fprintf('Run difference analysis:   %d\n', run_difference_analysis);

if isempty(group_mask)
    fprintf('Explicit group mask:       none\n');
else
    fprintf('Explicit group mask:       %s\n', group_mask);
end

fprintf('============================================================\n');

spm('defaults', 'FMRI');
spm_jobman('initcfg');

%% ========================================================================
% 2. Collect paired RN and LE maps
% ========================================================================

subject_directories = dir( ...
    fullfile( ...
        mean_root, ...
        'Sub*' ...
    ) ...
);

subject_directories = subject_directories( ...
    [subject_directories.isdir] ...
);

if isempty(subject_directories)
    error( ...
        'No participant directories matching Sub* were found in:\n%s', ...
        mean_root ...
    );
end

subject_directories = natural_sort_directory_struct( ...
    subject_directories ...
);

rn_files = {};
le_files = {};
included_subjects = {};
excluded_subjects = {};

for subject_index = 1:numel(subject_directories)

    subject_name = subject_directories(subject_index).name;
    subject_root = fullfile( ...
        mean_root, ...
        subject_name ...
    );

    rn_file = find_stage_mean_file( ...
        subject_root, ...
        'RN' ...
    );

    le_file = find_stage_mean_file( ...
        subject_root, ...
        'LE' ...
    );

    if ~isempty(rn_file) && ~isempty(le_file)

        rn_files{end + 1, 1} = ...
            add_volume_index(rn_file); %#ok<AGROW>

        le_files{end + 1, 1} = ...
            add_volume_index(le_file); %#ok<AGROW>

        included_subjects{end + 1, 1} = ...
            subject_name; %#ok<AGROW>

        fprintf( ...
            '[%s] Included\n', ...
            subject_name ...
        );

    else
        missing_items = {};

        if isempty(rn_file)
            missing_items{end + 1} = 'RN'; %#ok<AGROW>
        end

        if isempty(le_file)
            missing_items{end + 1} = 'LE'; %#ok<AGROW>
        end

        reason = sprintf( ...
            'Missing %s mean map', ...
            strjoin(missing_items, ' and ') ...
        );

        excluded_subjects(end + 1, :) = { ...
            subject_name, ...
            reason ...
        }; %#ok<AGROW>

        fprintf( ...
            '[%s] Skipped: %s\n', ...
            subject_name, ...
            reason ...
        );
    end
end

number_of_subjects = numel(rn_files);

if number_of_subjects == 0
    error( ...
        ['No paired RN and LE mean maps were found. ', ...
         'Check mean_root and the input filename structure.'] ...
    );
end

if number_of_subjects < 2
    error( ...
        ['At least two participants are required for a group-level ', ...
         'paired-samples t-test. Found: %d'], ...
        number_of_subjects ...
    );
end

fprintf( ...
    '\nParticipants entering the paired t-test: %d\n', ...
    number_of_subjects ...
);

%% ========================================================================
% 3. Validate image grids
% ========================================================================

validate_image_grids( ...
    rn_files, ...
    le_files, ...
    included_subjects ...
);

%% ========================================================================
% 4. Save participant inclusion manifest
% ========================================================================

manifest_path = fullfile( ...
    paired_stats_dir, ...
    'included_subjects.tsv' ...
);

manifest_file = fopen( ...
    manifest_path, ...
    'w' ...
);

if manifest_file == -1
    error( ...
        'Cannot create inclusion manifest:\n%s', ...
        manifest_path ...
    );
end

fprintf( ...
    manifest_file, ...
    'participant_id\tRN_file\tLE_file\n' ...
);

for subject_index = 1:number_of_subjects

    fprintf( ...
        manifest_file, ...
        '%s\t%s\t%s\n', ...
        included_subjects{subject_index}, ...
        remove_volume_index(rn_files{subject_index}), ...
        remove_volume_index(le_files{subject_index}) ...
    );
end

fclose(manifest_file);

if ~isempty(excluded_subjects)

    excluded_path = fullfile( ...
        paired_stats_dir, ...
        'excluded_subjects.tsv' ...
    );

    excluded_file = fopen( ...
        excluded_path, ...
        'w' ...
    );

    if excluded_file ~= -1

        fprintf( ...
            excluded_file, ...
            'participant_id\treason\n' ...
        );

        for excluded_index = 1:size(excluded_subjects, 1)

            fprintf( ...
                excluded_file, ...
                '%s\t%s\n', ...
                excluded_subjects{excluded_index, 1}, ...
                excluded_subjects{excluded_index, 2} ...
            );
        end

        fclose(excluded_file);
    end
end

%% ========================================================================
% 5. Paired-samples t-test: RN versus LE
% ========================================================================

paired_batch = {};

paired_batch{1}.spm.stats.factorial_design.dir = {
    paired_stats_dir
};

paired_batch{1}.spm.stats.factorial_design.des.pt.pair = ...
    struct( ...
        'scans', {} ...
    );

for subject_index = 1:number_of_subjects

    paired_batch{1}.spm.stats.factorial_design ...
        .des.pt.pair(subject_index).scans = {
            rn_files{subject_index}
            le_files{subject_index}
        };
end

paired_batch{1}.spm.stats.factorial_design.cov = ...
    struct( ...
        'c', {}, ...
        'cname', {}, ...
        'iCFI', {}, ...
        'iCC', {} ...
    );

paired_batch{1}.spm.stats.factorial_design ...
    .masking.tm.tm_none = 1;

paired_batch{1}.spm.stats.factorial_design ...
    .masking.im = 1;

if isempty(group_mask)

    paired_batch{1}.spm.stats.factorial_design ...
        .masking.em = {''};

else
    paired_batch{1}.spm.stats.factorial_design ...
        .masking.em = {
            add_volume_index(group_mask)
        };
end

paired_batch{1}.spm.stats.factorial_design ...
    .globalc.g_omit = 1;

paired_batch{1}.spm.stats.factorial_design ...
    .globalm.gmsca.gmsca_no = 1;

paired_batch{1}.spm.stats.factorial_design ...
    .globalm.glonorm = 1;

paired_spm_path = fullfile( ...
    paired_stats_dir, ...
    'SPM.mat' ...
);

paired_batch{2}.spm.stats.fmri_est.spmmat = {
    paired_spm_path
};

paired_batch{2}.spm.stats.fmri_est ...
    .write_residuals = 0;

paired_batch{2}.spm.stats.fmri_est ...
    .method.Classical = 1;

paired_batch{3}.spm.stats.con.spmmat = {
    paired_spm_path
};

paired_batch{3}.spm.stats.con.delete = 1;

paired_batch{3}.spm.stats.con.consess{1} ...
    .tcon.name = 'RN > LE';

paired_batch{3}.spm.stats.con.consess{1} ...
    .tcon.weights = [1, -1];

paired_batch{3}.spm.stats.con.consess{1} ...
    .tcon.sessrep = 'none';

paired_batch{3}.spm.stats.con.consess{2} ...
    .tcon.name = 'RN < LE';

paired_batch{3}.spm.stats.con.consess{2} ...
    .tcon.weights = [-1, 1];

paired_batch{3}.spm.stats.con.consess{2} ...
    .tcon.sessrep = 'none';

paired_batch_path = fullfile( ...
    paired_stats_dir, ...
    'batch_RN_vs_LE_paired_t.mat' ...
);

save( ...
    paired_batch_path, ...
    'paired_batch' ...
);

fprintf('\nRunning paired-samples t-test...\n');
fprintf('Participants: %d\n', number_of_subjects);
fprintf('Output: %s\n', paired_stats_dir);

spm_jobman( ...
    'run', ...
    paired_batch ...
);

fprintf('Paired-samples t-test completed.\n');

%% ========================================================================
% 6. Optional difference images and one-sample t-test
% ========================================================================

difference_analysis_completed = false;

if run_difference_analysis

    difference_image_dir = fullfile( ...
        difference_stats_dir, ...
        'difference_images' ...
    );

    if exist(difference_image_dir, 'dir') ~= 7
        mkdir(difference_image_dir);
    end

    difference_batch = {};

    for subject_index = 1:number_of_subjects

        subject_name = included_subjects{subject_index};

        output_filename = sprintf( ...
            '%s_RN_minus_LE.nii', ...
            subject_name ...
        );

        difference_batch{subject_index} ...
            .spm.util.imcalc.input = {
                rn_files{subject_index}
                le_files{subject_index}
            };

        difference_batch{subject_index} ...
            .spm.util.imcalc.output = ...
            output_filename;

        difference_batch{subject_index} ...
            .spm.util.imcalc.outdir = {
                difference_image_dir
            };

        difference_batch{subject_index} ...
            .spm.util.imcalc.expression = ...
            'i1 - i2';

        difference_batch{subject_index} ...
            .spm.util.imcalc.var = ...
            struct( ...
                'name', {}, ...
                'value', {} ...
            );

        difference_batch{subject_index} ...
            .spm.util.imcalc.options.dmtx = 0;

        difference_batch{subject_index} ...
            .spm.util.imcalc.options.mask = 0;

        difference_batch{subject_index} ...
            .spm.util.imcalc.options.interp = 1;

        % SPM datatype 16 corresponds to float32.
        difference_batch{subject_index} ...
            .spm.util.imcalc.options.dtype = 16;
    end

    difference_batch_path = fullfile( ...
        difference_stats_dir, ...
        'batch_create_RN_minus_LE_images.mat' ...
    );

    save( ...
        difference_batch_path, ...
        'difference_batch' ...
    );

    fprintf('\nCreating participant-level RN - LE images...\n');

    spm_jobman( ...
        'run', ...
        difference_batch ...
    );

    difference_scans = cell( ...
        number_of_subjects, ...
        1 ...
    );

    valid_difference_images = true( ...
        number_of_subjects, ...
        1 ...
    );

    for subject_index = 1:number_of_subjects

        difference_path = fullfile( ...
            difference_image_dir, ...
            sprintf( ...
                '%s_RN_minus_LE.nii', ...
                included_subjects{subject_index} ...
            ) ...
        );

        if exist(difference_path, 'file') == 2

            difference_scans{subject_index} = ...
                add_volume_index(difference_path);

        else
            valid_difference_images(subject_index) = false;

            warning( ...
                'Difference image was not generated: %s', ...
                difference_path ...
            );
        end
    end

    difference_scans = difference_scans( ...
        valid_difference_images ...
    );

    if numel(difference_scans) < 2

        warning( ...
            ['Fewer than two valid difference images were generated. ', ...
             'The one-sample t-test will be skipped.'] ...
        );

    else
        one_sample_batch = {};

        one_sample_batch{1}.spm.stats ...
            .factorial_design.dir = {
                difference_stats_dir
            };

        one_sample_batch{1}.spm.stats ...
            .factorial_design.des.t1.scans = ...
            difference_scans;

        one_sample_batch{1}.spm.stats ...
            .factorial_design.cov = ...
            struct( ...
                'c', {}, ...
                'cname', {}, ...
                'iCFI', {}, ...
                'iCC', {} ...
            );

        one_sample_batch{1}.spm.stats ...
            .factorial_design.masking.tm.tm_none = 1;

        one_sample_batch{1}.spm.stats ...
            .factorial_design.masking.im = 1;

        if isempty(group_mask)

            one_sample_batch{1}.spm.stats ...
                .factorial_design.masking.em = {''};

        else
            one_sample_batch{1}.spm.stats ...
                .factorial_design.masking.em = {
                    add_volume_index(group_mask)
                };
        end

        one_sample_batch{1}.spm.stats ...
            .factorial_design.globalc.g_omit = 1;

        one_sample_batch{1}.spm.stats ...
            .factorial_design.globalm.gmsca.gmsca_no = 1;

        one_sample_batch{1}.spm.stats ...
            .factorial_design.globalm.glonorm = 1;

        one_sample_spm_path = fullfile( ...
            difference_stats_dir, ...
            'SPM.mat' ...
        );

        one_sample_batch{2}.spm.stats ...
            .fmri_est.spmmat = {
                one_sample_spm_path
            };

        one_sample_batch{2}.spm.stats ...
            .fmri_est.write_residuals = 0;

        one_sample_batch{2}.spm.stats ...
            .fmri_est.method.Classical = 1;

        one_sample_batch{3}.spm.stats ...
            .con.spmmat = {
                one_sample_spm_path
            };

        one_sample_batch{3}.spm.stats ...
            .con.delete = 1;

        one_sample_batch{3}.spm.stats ...
            .con.consess{1}.tcon.name = ...
            'RN - LE > 0';

        one_sample_batch{3}.spm.stats ...
            .con.consess{1}.tcon.weights = 1;

        one_sample_batch{3}.spm.stats ...
            .con.consess{1}.tcon.sessrep = ...
            'none';

        one_sample_batch{3}.spm.stats ...
            .con.consess{2}.tcon.name = ...
            'RN - LE < 0';

        one_sample_batch{3}.spm.stats ...
            .con.consess{2}.tcon.weights = -1;

        one_sample_batch{3}.spm.stats ...
            .con.consess{2}.tcon.sessrep = ...
            'none';

        one_sample_batch_path = fullfile( ...
            difference_stats_dir, ...
            'batch_RN_minus_LE_one_sample_t.mat' ...
        );

        save( ...
            one_sample_batch_path, ...
            'one_sample_batch' ...
        );

        fprintf( ...
            '\nRunning one-sample t-test on RN - LE images...\n' ...
        );

        fprintf( ...
            'Difference images: %d\n', ...
            numel(difference_scans) ...
        );

        fprintf( ...
            'Output: %s\n', ...
            difference_stats_dir ...
        );

        spm_jobman( ...
            'run', ...
            one_sample_batch ...
        );

        difference_analysis_completed = true;

        fprintf( ...
            'Difference-image one-sample t-test completed.\n' ...
        );
    end
end

%% ========================================================================
% 7. Completion summary
% ========================================================================

fprintf('\n============================================================\n');
fprintf('Analysis completed\n');
fprintf('============================================================\n');

fprintf( ...
    'Paired-samples t-test: completed with %d participants\n', ...
    number_of_subjects ...
);

if ~run_difference_analysis

    fprintf( ...
        'Difference-image analysis: not requested\n' ...
    );

elseif difference_analysis_completed

    fprintf( ...
        'Difference-image analysis: completed\n' ...
    );

else
    fprintf( ...
        'Difference-image analysis: requested but not completed\n' ...
    );
end

fprintf('============================================================\n');

end


%% ========================================================================
% Local helper functions
% ========================================================================

function stage_file = find_stage_mean_file( ...
    subject_root, ...
    stage_name ...
)
% Locate a stage mean image using supported naming schemes.
%
% Preferred:
%   <subject>/<stage>/pattern_change_mean_<stage>.nii
%
% Alternative:
%   <subject>/<stage>_mean.nii
%
% Both .nii and .nii.gz are supported.

preferred_base = fullfile( ...
    subject_root, ...
    stage_name, ...
    sprintf( ...
        'pattern_change_mean_%s', ...
        stage_name ...
    ) ...
);

alternative_base = fullfile( ...
    subject_root, ...
    sprintf( ...
        '%s_mean', ...
        stage_name ...
    ) ...
);

candidates = {
    [preferred_base, '.nii'], ...
    [preferred_base, '.nii.gz'], ...
    [alternative_base, '.nii'], ...
    [alternative_base, '.nii.gz'] ...
};

stage_file = '';

for candidate_index = 1:numel(candidates)

    if exist(candidates{candidate_index}, 'file') == 2

        stage_file = candidates{candidate_index};
        return;
    end
end

end


function indexed_path = add_volume_index(file_path)
% Add the SPM volume suffix ",1" when it is absent.

file_path = char(file_path);

if ~isempty( ...
        regexp( ...
            file_path, ...
            ',\d+$', ...
            'once' ...
        ) ...
    )

    indexed_path = file_path;
else
    indexed_path = [
        file_path, ...
        ',1' ...
    ];
end

end


function clean_path = remove_volume_index(indexed_path)
% Remove a trailing SPM volume suffix such as ",1".

clean_path = regexprep( ...
    char(indexed_path), ...
    ',\d+$', ...
    '' ...
);

end


function validate_image_grids( ...
    rn_files, ...
    le_files, ...
    subject_names ...
)
% Confirm that all paired maps share the same voxel grid and affine.

reference_path = remove_volume_index( ...
    rn_files{1} ...
);

reference_volume = spm_vol( ...
    reference_path ...
);

reference_dimensions = ...
    reference_volume(1).dim;

reference_affine = ...
    reference_volume(1).mat;

affine_tolerance = 1e-4;

for subject_index = 1:numel(rn_files)

    current_paths = {
        remove_volume_index(rn_files{subject_index}), ...
        remove_volume_index(le_files{subject_index}) ...
    };

    current_labels = {
        'RN', ...
        'LE' ...
    };

    for image_index = 1:numel(current_paths)

        current_volume = spm_vol( ...
            current_paths{image_index} ...
        );

        current_dimensions = ...
            current_volume(1).dim;

        current_affine = ...
            current_volume(1).mat;

        if ~isequal( ...
                current_dimensions, ...
                reference_dimensions ...
            )

            error( ...
                ['Image dimensions do not match the reference grid.\n', ...
                 'Participant: %s\nStage: %s\nFile: %s'], ...
                subject_names{subject_index}, ...
                current_labels{image_index}, ...
                current_paths{image_index} ...
            );
        end

        if max( ...
                abs( ...
                    current_affine(:) ...
                    - reference_affine(:) ...
                ) ...
            ) > affine_tolerance

            error( ...
                ['Image affine does not match the reference grid.\n', ...
                 'Participant: %s\nStage: %s\nFile: %s'], ...
                subject_names{subject_index}, ...
                current_labels{image_index}, ...
                current_paths{image_index} ...
            );
        end
    end
end

fprintf( ...
    'Image-grid validation passed for %d participants.\n', ...
    numel(subject_names) ...
);

end


function sorted_directories = natural_sort_directory_struct( ...
    directory_struct ...
)
% Sort participant folders by the numeric part of their names.

participant_numbers = nan( ...
    numel(directory_struct), ...
    1 ...
);

for directory_index = 1:numel(directory_struct)

    numeric_token = regexp( ...
        directory_struct(directory_index).name, ...
        '\d+', ...
        'match', ...
        'once' ...
    );

    participant_numbers(directory_index) = ...
        str2double(numeric_token);
end

[~, sorting_order] = sort( ...
    participant_numbers ...
);

sorted_directories = directory_struct( ...
    sorting_order ...
);

end


function prepare_output_directory( ...
    output_directory, ...
    overwrite_existing ...
)
% Create the output directory and optionally remove an existing SPM model.

if exist(output_directory, 'dir') ~= 7

    mkdir(output_directory);
    return;
end

existing_spm = fullfile( ...
    output_directory, ...
    'SPM.mat' ...
);

if exist(existing_spm, 'file') == 2

    if overwrite_existing

        files_to_remove = {
            'SPM.mat', ...
            'mask.nii', ...
            'ResMS.nii', ...
            'RPV.nii', ...
            'beta_*.nii', ...
            'con_*.nii', ...
            'ess_*.nii', ...
            'spmT_*.nii', ...
            'spmF_*.nii' ...
        };

        for pattern_index = 1:numel(files_to_remove)

            matching_files = dir( ...
                fullfile( ...
                    output_directory, ...
                    files_to_remove{pattern_index} ...
                ) ...
            );

            for file_index = 1:numel(matching_files)

                file_path = fullfile( ...
                    output_directory, ...
                    matching_files(file_index).name ...
                );

                if exist(file_path, 'file') == 2
                    delete(file_path);
                end
            end
        end

    else
        error( ...
            ['An existing SPM model was found in:\n%s\n', ...
             'Set overwrite_existing_stats=true to replace it.'], ...
            output_directory ...
        );
    end
end

end